// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AccessControlHandle : RemoteTableHandle<EventContext, AccessControl>
        {
            protected override string RemoteTableName => "access_control";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(AccessControl row) => row.Id;

                public IdUniqueIndex(AccessControlHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal AccessControlHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(AccessControl row) => row.Id;
        }

        public readonly AccessControlHandle AccessControl;
    }

    public sealed class AccessControlCols
    {
        public global::SpacetimeDB.Col<AccessControl, ulong> Id { get; }
        public global::SpacetimeDB.Col<AccessControl, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<AccessControl, string> EntityTable { get; }
        public global::SpacetimeDB.Col<AccessControl, SpacetimeDB.Identity> OwnerId { get; }
        public global::SpacetimeDB.Col<AccessControl, bool> IsPublic { get; }

        public AccessControlCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<AccessControl, ulong>(tableName, "id");
            EntityId = new global::SpacetimeDB.Col<AccessControl, ulong>(tableName, "entity_id");
            EntityTable = new global::SpacetimeDB.Col<AccessControl, string>(tableName, "entity_table");
            OwnerId = new global::SpacetimeDB.Col<AccessControl, SpacetimeDB.Identity>(tableName, "owner_id");
            IsPublic = new global::SpacetimeDB.Col<AccessControl, bool>(tableName, "is_public");
        }
    }

    public sealed class AccessControlIxCols
    {
        public global::SpacetimeDB.IxCol<AccessControl, ulong> Id { get; }

        public AccessControlIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<AccessControl, ulong>(tableName, "id");
        }
    }
}
