// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AdminListHandle : RemoteTableHandle<EventContext, AdminList>
        {
            protected override string RemoteTableName => "admin_list";

            public sealed class PlayerIdUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(AdminList row) => row.PlayerId;

                public PlayerIdUniqueIndex(AdminListHandle table) : base(table) { }
            }

            public readonly PlayerIdUniqueIndex PlayerId;

            internal AdminListHandle(DbConnection conn) : base(conn)
            {
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(AdminList row) => row.PlayerId;
        }

        public readonly AdminListHandle AdminList;
    }

    public sealed class AdminListCols
    {
        public global::SpacetimeDB.Col<AdminList, SpacetimeDB.Identity> PlayerId { get; }

        public AdminListCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.Col<AdminList, SpacetimeDB.Identity>(tableName, "player_id");
        }
    }

    public sealed class AdminListIxCols
    {
        public global::SpacetimeDB.IxCol<AdminList, SpacetimeDB.Identity> PlayerId { get; }

        public AdminListIxCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.IxCol<AdminList, SpacetimeDB.Identity>(tableName, "player_id");
        }
    }
}
