// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ArcadeSessionHandle : RemoteTableHandle<EventContext, ArcadeSession>
        {
            protected override string RemoteTableName => "arcade_session";

            public sealed class MachineIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ArcadeSession row) => row.MachineId;

                public MachineIdUniqueIndex(ArcadeSessionHandle table) : base(table) { }
            }

            public readonly MachineIdUniqueIndex MachineId;

            internal ArcadeSessionHandle(DbConnection conn) : base(conn)
            {
                MachineId = new(this);
            }

            protected override object GetPrimaryKey(ArcadeSession row) => row.MachineId;
        }

        public readonly ArcadeSessionHandle ArcadeSession;
    }

    public sealed class ArcadeSessionCols
    {
        public global::SpacetimeDB.Col<ArcadeSession, ulong> MachineId { get; }
        public global::SpacetimeDB.Col<ArcadeSession, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.Col<ArcadeSession, byte> GameType { get; }
        public global::SpacetimeDB.Col<ArcadeSession, byte> State { get; }
        public global::SpacetimeDB.Col<ArcadeSession, ulong> Bet { get; }
        public global::SpacetimeDB.Col<ArcadeSession, string> ChallengeData { get; }
        public global::SpacetimeDB.Col<ArcadeSession, ulong> StartTime { get; }
        public global::SpacetimeDB.Col<ArcadeSession, ulong> ExpiresAt { get; }

        public ArcadeSessionCols(string tableName)
        {
            MachineId = new global::SpacetimeDB.Col<ArcadeSession, ulong>(tableName, "machine_id");
            PlayerId = new global::SpacetimeDB.Col<ArcadeSession, SpacetimeDB.Identity>(tableName, "player_id");
            GameType = new global::SpacetimeDB.Col<ArcadeSession, byte>(tableName, "game_type");
            State = new global::SpacetimeDB.Col<ArcadeSession, byte>(tableName, "state");
            Bet = new global::SpacetimeDB.Col<ArcadeSession, ulong>(tableName, "bet");
            ChallengeData = new global::SpacetimeDB.Col<ArcadeSession, string>(tableName, "challenge_data");
            StartTime = new global::SpacetimeDB.Col<ArcadeSession, ulong>(tableName, "start_time");
            ExpiresAt = new global::SpacetimeDB.Col<ArcadeSession, ulong>(tableName, "expires_at");
        }
    }

    public sealed class ArcadeSessionIxCols
    {
        public global::SpacetimeDB.IxCol<ArcadeSession, ulong> MachineId { get; }

        public ArcadeSessionIxCols(string tableName)
        {
            MachineId = new global::SpacetimeDB.IxCol<ArcadeSession, ulong>(tableName, "machine_id");
        }
    }
}
