// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BlackjackGameHandle : RemoteTableHandle<EventContext, BlackjackGame>
        {
            protected override string RemoteTableName => "blackjack_game";

            public sealed class MachineIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(BlackjackGame row) => row.MachineId;

                public MachineIdUniqueIndex(BlackjackGameHandle table) : base(table) { }
            }

            public readonly MachineIdUniqueIndex MachineId;

            internal BlackjackGameHandle(DbConnection conn) : base(conn)
            {
                MachineId = new(this);
            }

            protected override object GetPrimaryKey(BlackjackGame row) => row.MachineId;
        }

        public readonly BlackjackGameHandle BlackjackGame;
    }

    public sealed class BlackjackGameCols
    {
        public global::SpacetimeDB.Col<BlackjackGame, ulong> MachineId { get; }
        public global::SpacetimeDB.Col<BlackjackGame, byte> State { get; }
        public global::SpacetimeDB.Col<BlackjackGame, string> DealerHand { get; }
        public global::SpacetimeDB.Col<BlackjackGame, string> DealerHandHidden { get; }
        public global::SpacetimeDB.Col<BlackjackGame, string> Deck { get; }
        public global::SpacetimeDB.Col<BlackjackGame, uint> RoundId { get; }

        public BlackjackGameCols(string tableName)
        {
            MachineId = new global::SpacetimeDB.Col<BlackjackGame, ulong>(tableName, "machine_id");
            State = new global::SpacetimeDB.Col<BlackjackGame, byte>(tableName, "state");
            DealerHand = new global::SpacetimeDB.Col<BlackjackGame, string>(tableName, "dealer_hand");
            DealerHandHidden = new global::SpacetimeDB.Col<BlackjackGame, string>(tableName, "dealer_hand_hidden");
            Deck = new global::SpacetimeDB.Col<BlackjackGame, string>(tableName, "deck");
            RoundId = new global::SpacetimeDB.Col<BlackjackGame, uint>(tableName, "round_id");
        }
    }

    public sealed class BlackjackGameIxCols
    {
        public global::SpacetimeDB.IxCol<BlackjackGame, ulong> MachineId { get; }

        public BlackjackGameIxCols(string tableName)
        {
            MachineId = new global::SpacetimeDB.IxCol<BlackjackGame, ulong>(tableName, "machine_id");
        }
    }
}
