// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BlackjackSeatHandle : RemoteTableHandle<EventContext, BlackjackSeat>
        {
            protected override string RemoteTableName => "blackjack_seat";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(BlackjackSeat row) => row.Id;

                public IdUniqueIndex(BlackjackSeatHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal BlackjackSeatHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(BlackjackSeat row) => row.Id;
        }

        public readonly BlackjackSeatHandle BlackjackSeat;
    }

    public sealed class BlackjackSeatCols
    {
        public global::SpacetimeDB.Col<BlackjackSeat, ulong> Id { get; }
        public global::SpacetimeDB.Col<BlackjackSeat, ulong> MachineId { get; }
        public global::SpacetimeDB.Col<BlackjackSeat, byte> SeatIndex { get; }
        public global::SpacetimeDB.Col<BlackjackSeat, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.Col<BlackjackSeat, string> Hand { get; }
        public global::SpacetimeDB.Col<BlackjackSeat, ulong> Bet { get; }
        public global::SpacetimeDB.Col<BlackjackSeat, byte> State { get; }
        public global::SpacetimeDB.Col<BlackjackSeat, uint> RoundId { get; }

        public BlackjackSeatCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<BlackjackSeat, ulong>(tableName, "id");
            MachineId = new global::SpacetimeDB.Col<BlackjackSeat, ulong>(tableName, "machine_id");
            SeatIndex = new global::SpacetimeDB.Col<BlackjackSeat, byte>(tableName, "seat_index");
            PlayerId = new global::SpacetimeDB.Col<BlackjackSeat, SpacetimeDB.Identity>(tableName, "player_id");
            Hand = new global::SpacetimeDB.Col<BlackjackSeat, string>(tableName, "hand");
            Bet = new global::SpacetimeDB.Col<BlackjackSeat, ulong>(tableName, "bet");
            State = new global::SpacetimeDB.Col<BlackjackSeat, byte>(tableName, "state");
            RoundId = new global::SpacetimeDB.Col<BlackjackSeat, uint>(tableName, "round_id");
        }
    }

    public sealed class BlackjackSeatIxCols
    {
        public global::SpacetimeDB.IxCol<BlackjackSeat, ulong> Id { get; }

        public BlackjackSeatIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<BlackjackSeat, ulong>(tableName, "id");
        }
    }
}
