// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CoinPusherStateHandle : RemoteTableHandle<EventContext, CoinPusherState>
        {
            protected override string RemoteTableName => "coin_pusher_state";

            public sealed class MachineIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(CoinPusherState row) => row.MachineId;

                public MachineIdUniqueIndex(CoinPusherStateHandle table) : base(table) { }
            }

            public readonly MachineIdUniqueIndex MachineId;

            internal CoinPusherStateHandle(DbConnection conn) : base(conn)
            {
                MachineId = new(this);
            }

            protected override object GetPrimaryKey(CoinPusherState row) => row.MachineId;
        }

        public readonly CoinPusherStateHandle CoinPusherState;
    }

    public sealed class CoinPusherStateCols
    {
        public global::SpacetimeDB.Col<CoinPusherState, ulong> MachineId { get; }
        public global::SpacetimeDB.Col<CoinPusherState, uint> CoinCount { get; }
        public global::SpacetimeDB.Col<CoinPusherState, ulong> CopperPool { get; }
        public global::SpacetimeDB.Col<CoinPusherState, SpacetimeDB.Identity> LastPusherId { get; }
        public global::SpacetimeDB.Col<CoinPusherState, ulong> LastPushTime { get; }
        public global::SpacetimeDB.Col<CoinPusherState, uint> JackpotThreshold { get; }

        public CoinPusherStateCols(string tableName)
        {
            MachineId = new global::SpacetimeDB.Col<CoinPusherState, ulong>(tableName, "machine_id");
            CoinCount = new global::SpacetimeDB.Col<CoinPusherState, uint>(tableName, "coin_count");
            CopperPool = new global::SpacetimeDB.Col<CoinPusherState, ulong>(tableName, "copper_pool");
            LastPusherId = new global::SpacetimeDB.Col<CoinPusherState, SpacetimeDB.Identity>(tableName, "last_pusher_id");
            LastPushTime = new global::SpacetimeDB.Col<CoinPusherState, ulong>(tableName, "last_push_time");
            JackpotThreshold = new global::SpacetimeDB.Col<CoinPusherState, uint>(tableName, "jackpot_threshold");
        }
    }

    public sealed class CoinPusherStateIxCols
    {
        public global::SpacetimeDB.IxCol<CoinPusherState, ulong> MachineId { get; }

        public CoinPusherStateIxCols(string tableName)
        {
            MachineId = new global::SpacetimeDB.IxCol<CoinPusherState, ulong>(tableName, "machine_id");
        }
    }
}
