// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ContainerSlotHandle : RemoteTableHandle<EventContext, ContainerSlot>
        {
            protected override string RemoteTableName => "container_slot";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ContainerSlot row) => row.Id;

                public IdUniqueIndex(ContainerSlotHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ContainerSlotHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ContainerSlot row) => row.Id;
        }

        public readonly ContainerSlotHandle ContainerSlot;
    }

    public sealed class ContainerSlotCols
    {
        public global::SpacetimeDB.Col<ContainerSlot, ulong> Id { get; }
        public global::SpacetimeDB.Col<ContainerSlot, ulong> ContainerId { get; }
        public global::SpacetimeDB.Col<ContainerSlot, string> ContainerTable { get; }
        public global::SpacetimeDB.Col<ContainerSlot, int> Slot { get; }
        public global::SpacetimeDB.Col<ContainerSlot, string> ItemType { get; }
        public global::SpacetimeDB.Col<ContainerSlot, uint> Quantity { get; }

        public ContainerSlotCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ContainerSlot, ulong>(tableName, "id");
            ContainerId = new global::SpacetimeDB.Col<ContainerSlot, ulong>(tableName, "container_id");
            ContainerTable = new global::SpacetimeDB.Col<ContainerSlot, string>(tableName, "container_table");
            Slot = new global::SpacetimeDB.Col<ContainerSlot, int>(tableName, "slot");
            ItemType = new global::SpacetimeDB.Col<ContainerSlot, string>(tableName, "item_type");
            Quantity = new global::SpacetimeDB.Col<ContainerSlot, uint>(tableName, "quantity");
        }
    }

    public sealed class ContainerSlotIxCols
    {
        public global::SpacetimeDB.IxCol<ContainerSlot, ulong> Id { get; }

        public ContainerSlotIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ContainerSlot, ulong>(tableName, "id");
        }
    }
}
