// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CraftingRecipeHandle : RemoteTableHandle<EventContext, CraftingRecipe>
        {
            protected override string RemoteTableName => "crafting_recipe";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(CraftingRecipe row) => row.Id;

                public IdUniqueIndex(CraftingRecipeHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal CraftingRecipeHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(CraftingRecipe row) => row.Id;
        }

        public readonly CraftingRecipeHandle CraftingRecipe;
    }

    public sealed class CraftingRecipeCols
    {
        public global::SpacetimeDB.Col<CraftingRecipe, ulong> Id { get; }
        public global::SpacetimeDB.Col<CraftingRecipe, string> ResultItemType { get; }
        public global::SpacetimeDB.Col<CraftingRecipe, uint> ResultQuantity { get; }
        public global::SpacetimeDB.Col<CraftingRecipe, string> Ingredients { get; }
        public global::SpacetimeDB.Col<CraftingRecipe, float> CraftTimeSeconds { get; }

        public CraftingRecipeCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<CraftingRecipe, ulong>(tableName, "id");
            ResultItemType = new global::SpacetimeDB.Col<CraftingRecipe, string>(tableName, "result_item_type");
            ResultQuantity = new global::SpacetimeDB.Col<CraftingRecipe, uint>(tableName, "result_quantity");
            Ingredients = new global::SpacetimeDB.Col<CraftingRecipe, string>(tableName, "ingredients");
            CraftTimeSeconds = new global::SpacetimeDB.Col<CraftingRecipe, float>(tableName, "craft_time_seconds");
        }
    }

    public sealed class CraftingRecipeIxCols
    {
        public global::SpacetimeDB.IxCol<CraftingRecipe, ulong> Id { get; }

        public CraftingRecipeIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<CraftingRecipe, ulong>(tableName, "id");
        }
    }
}
