// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CurrencyTransactionHandle : RemoteTableHandle<EventContext, CurrencyTransaction>
        {
            protected override string RemoteTableName => "currency_transaction";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(CurrencyTransaction row) => row.Id;

                public IdUniqueIndex(CurrencyTransactionHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal CurrencyTransactionHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(CurrencyTransaction row) => row.Id;
        }

        public readonly CurrencyTransactionHandle CurrencyTransaction;
    }

    public sealed class CurrencyTransactionCols
    {
        public global::SpacetimeDB.Col<CurrencyTransaction, ulong> Id { get; }
        public global::SpacetimeDB.Col<CurrencyTransaction, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.Col<CurrencyTransaction, long> Amount { get; }
        public global::SpacetimeDB.Col<CurrencyTransaction, string> Reason { get; }
        public global::SpacetimeDB.Col<CurrencyTransaction, ulong> Timestamp { get; }

        public CurrencyTransactionCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<CurrencyTransaction, ulong>(tableName, "id");
            PlayerId = new global::SpacetimeDB.Col<CurrencyTransaction, SpacetimeDB.Identity>(tableName, "player_id");
            Amount = new global::SpacetimeDB.Col<CurrencyTransaction, long>(tableName, "amount");
            Reason = new global::SpacetimeDB.Col<CurrencyTransaction, string>(tableName, "reason");
            Timestamp = new global::SpacetimeDB.Col<CurrencyTransaction, ulong>(tableName, "timestamp");
        }
    }

    public sealed class CurrencyTransactionIxCols
    {
        public global::SpacetimeDB.IxCol<CurrencyTransaction, ulong> Id { get; }

        public CurrencyTransactionIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<CurrencyTransaction, ulong>(tableName, "id");
        }
    }
}
