// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CurrencyBalanceHandle : RemoteTableHandle<EventContext, CurrencyBalance>
        {
            protected override string RemoteTableName => "currency_balance";

            public sealed class PlayerIdUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(CurrencyBalance row) => row.PlayerId;

                public PlayerIdUniqueIndex(CurrencyBalanceHandle table) : base(table) { }
            }

            public readonly PlayerIdUniqueIndex PlayerId;

            internal CurrencyBalanceHandle(DbConnection conn) : base(conn)
            {
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(CurrencyBalance row) => row.PlayerId;
        }

        public readonly CurrencyBalanceHandle CurrencyBalance;
    }

    public sealed class CurrencyBalanceCols
    {
        public global::SpacetimeDB.Col<CurrencyBalance, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.Col<CurrencyBalance, ulong> Copper { get; }

        public CurrencyBalanceCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.Col<CurrencyBalance, SpacetimeDB.Identity>(tableName, "player_id");
            Copper = new global::SpacetimeDB.Col<CurrencyBalance, ulong>(tableName, "copper");
        }
    }

    public sealed class CurrencyBalanceIxCols
    {
        public global::SpacetimeDB.IxCol<CurrencyBalance, SpacetimeDB.Identity> PlayerId { get; }

        public CurrencyBalanceIxCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.IxCol<CurrencyBalance, SpacetimeDB.Identity>(tableName, "player_id");
        }
    }
}
