// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DamageEventHandle : RemoteTableHandle<EventContext, DamageEvent>
        {
            protected override string RemoteTableName => "damage_event";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(DamageEvent row) => row.Id;

                public IdUniqueIndex(DamageEventHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal DamageEventHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(DamageEvent row) => row.Id;
        }

        public readonly DamageEventHandle DamageEvent;
    }

    public sealed class DamageEventCols
    {
        public global::SpacetimeDB.Col<DamageEvent, ulong> Id { get; }
        public global::SpacetimeDB.Col<DamageEvent, ulong> SourceId { get; }
        public global::SpacetimeDB.Col<DamageEvent, string> SourceType { get; }
        public global::SpacetimeDB.Col<DamageEvent, ulong> TargetId { get; }
        public global::SpacetimeDB.Col<DamageEvent, string> TargetType { get; }
        public global::SpacetimeDB.Col<DamageEvent, int> Amount { get; }
        public global::SpacetimeDB.Col<DamageEvent, string> DamageType { get; }
        public global::SpacetimeDB.Col<DamageEvent, ulong> Timestamp { get; }

        public DamageEventCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<DamageEvent, ulong>(tableName, "id");
            SourceId = new global::SpacetimeDB.Col<DamageEvent, ulong>(tableName, "source_id");
            SourceType = new global::SpacetimeDB.Col<DamageEvent, string>(tableName, "source_type");
            TargetId = new global::SpacetimeDB.Col<DamageEvent, ulong>(tableName, "target_id");
            TargetType = new global::SpacetimeDB.Col<DamageEvent, string>(tableName, "target_type");
            Amount = new global::SpacetimeDB.Col<DamageEvent, int>(tableName, "amount");
            DamageType = new global::SpacetimeDB.Col<DamageEvent, string>(tableName, "damage_type");
            Timestamp = new global::SpacetimeDB.Col<DamageEvent, ulong>(tableName, "timestamp");
        }
    }

    public sealed class DamageEventIxCols
    {
        public global::SpacetimeDB.IxCol<DamageEvent, ulong> Id { get; }

        public DamageEventIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<DamageEvent, ulong>(tableName, "id");
        }
    }
}
