// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class HelloWorldMessageHandle : RemoteTableHandle<EventContext, HelloWorldMessage>
        {
            protected override string RemoteTableName => "hello_world_message";

            public sealed class PlayerIdUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(HelloWorldMessage row) => row.PlayerId;

                public PlayerIdUniqueIndex(HelloWorldMessageHandle table) : base(table) { }
            }

            public readonly PlayerIdUniqueIndex PlayerId;

            internal HelloWorldMessageHandle(DbConnection conn) : base(conn)
            {
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(HelloWorldMessage row) => row.PlayerId;
        }

        public readonly HelloWorldMessageHandle HelloWorldMessage;
    }

    public sealed class HelloWorldMessageCols
    {
        public global::SpacetimeDB.Col<HelloWorldMessage, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.Col<HelloWorldMessage, string> Message { get; }

        public HelloWorldMessageCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.Col<HelloWorldMessage, SpacetimeDB.Identity>(tableName, "player_id");
            Message = new global::SpacetimeDB.Col<HelloWorldMessage, string>(tableName, "message");
        }
    }

    public sealed class HelloWorldMessageIxCols
    {
        public global::SpacetimeDB.IxCol<HelloWorldMessage, SpacetimeDB.Identity> PlayerId { get; }

        public HelloWorldMessageIxCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.IxCol<HelloWorldMessage, SpacetimeDB.Identity>(tableName, "player_id");
        }
    }
}
