// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ModConfigHandle : RemoteTableHandle<EventContext, ModConfig>
        {
            protected override string RemoteTableName => "mod_config";

            public sealed class ModIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ModConfig row) => row.ModId;

                public ModIdUniqueIndex(ModConfigHandle table) : base(table) { }
            }

            public readonly ModIdUniqueIndex ModId;

            internal ModConfigHandle(DbConnection conn) : base(conn)
            {
                ModId = new(this);
            }

            protected override object GetPrimaryKey(ModConfig row) => row.ModId;
        }

        public readonly ModConfigHandle ModConfig;
    }

    public sealed class ModConfigCols
    {
        public global::SpacetimeDB.Col<ModConfig, string> ModId { get; }
        public global::SpacetimeDB.Col<ModConfig, bool> Enabled { get; }
        public global::SpacetimeDB.Col<ModConfig, string> Version { get; }
        public global::SpacetimeDB.Col<ModConfig, string> Dependencies { get; }

        public ModConfigCols(string tableName)
        {
            ModId = new global::SpacetimeDB.Col<ModConfig, string>(tableName, "mod_id");
            Enabled = new global::SpacetimeDB.Col<ModConfig, bool>(tableName, "enabled");
            Version = new global::SpacetimeDB.Col<ModConfig, string>(tableName, "version");
            Dependencies = new global::SpacetimeDB.Col<ModConfig, string>(tableName, "dependencies");
        }
    }

    public sealed class ModConfigIxCols
    {
        public global::SpacetimeDB.IxCol<ModConfig, string> ModId { get; }

        public ModConfigIxCols(string tableName)
        {
            ModId = new global::SpacetimeDB.IxCol<ModConfig, string>(tableName, "mod_id");
        }
    }
}
