// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NpcSpawnRuleHandle : RemoteTableHandle<EventContext, NpcSpawnRule>
        {
            protected override string RemoteTableName => "npc_spawn_rule";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(NpcSpawnRule row) => row.Id;

                public IdUniqueIndex(NpcSpawnRuleHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal NpcSpawnRuleHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(NpcSpawnRule row) => row.Id;
        }

        public readonly NpcSpawnRuleHandle NpcSpawnRule;
    }

    public sealed class NpcSpawnRuleCols
    {
        public global::SpacetimeDB.Col<NpcSpawnRule, ulong> Id { get; }
        public global::SpacetimeDB.Col<NpcSpawnRule, string> NpcType { get; }
        public global::SpacetimeDB.Col<NpcSpawnRule, float> ZoneX { get; }
        public global::SpacetimeDB.Col<NpcSpawnRule, float> ZoneZ { get; }
        public global::SpacetimeDB.Col<NpcSpawnRule, float> ZoneRadius { get; }
        public global::SpacetimeDB.Col<NpcSpawnRule, int> MaxCount { get; }
        public global::SpacetimeDB.Col<NpcSpawnRule, float> RespawnTimeSec { get; }

        public NpcSpawnRuleCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<NpcSpawnRule, ulong>(tableName, "id");
            NpcType = new global::SpacetimeDB.Col<NpcSpawnRule, string>(tableName, "npc_type");
            ZoneX = new global::SpacetimeDB.Col<NpcSpawnRule, float>(tableName, "zone_x");
            ZoneZ = new global::SpacetimeDB.Col<NpcSpawnRule, float>(tableName, "zone_z");
            ZoneRadius = new global::SpacetimeDB.Col<NpcSpawnRule, float>(tableName, "zone_radius");
            MaxCount = new global::SpacetimeDB.Col<NpcSpawnRule, int>(tableName, "max_count");
            RespawnTimeSec = new global::SpacetimeDB.Col<NpcSpawnRule, float>(tableName, "respawn_time_sec");
        }
    }

    public sealed class NpcSpawnRuleIxCols
    {
        public global::SpacetimeDB.IxCol<NpcSpawnRule, ulong> Id { get; }

        public NpcSpawnRuleIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<NpcSpawnRule, ulong>(tableName, "id");
        }
    }
}
