// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerHandle : RemoteTableHandle<EventContext, Player>
        {
            protected override string RemoteTableName => "player";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Player row) => row.Identity;

                public IdentityUniqueIndex(PlayerHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal PlayerHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(Player row) => row.Identity;
        }

        public readonly PlayerHandle Player;
    }

    public sealed class PlayerCols
    {
        public global::SpacetimeDB.Col<Player, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<Player, string> Name { get; }
        public global::SpacetimeDB.Col<Player, float> PosX { get; }
        public global::SpacetimeDB.Col<Player, float> PosY { get; }
        public global::SpacetimeDB.Col<Player, float> PosZ { get; }
        public global::SpacetimeDB.Col<Player, float> RotY { get; }
        public global::SpacetimeDB.Col<Player, float> Health { get; }
        public global::SpacetimeDB.Col<Player, float> MaxHealth { get; }
        public global::SpacetimeDB.Col<Player, float> Stamina { get; }
        public global::SpacetimeDB.Col<Player, float> MaxStamina { get; }
        public global::SpacetimeDB.Col<Player, bool> IsOnline { get; }

        public PlayerCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<Player, SpacetimeDB.Identity>(tableName, "identity");
            Name = new global::SpacetimeDB.Col<Player, string>(tableName, "name");
            PosX = new global::SpacetimeDB.Col<Player, float>(tableName, "pos_x");
            PosY = new global::SpacetimeDB.Col<Player, float>(tableName, "pos_y");
            PosZ = new global::SpacetimeDB.Col<Player, float>(tableName, "pos_z");
            RotY = new global::SpacetimeDB.Col<Player, float>(tableName, "rot_y");
            Health = new global::SpacetimeDB.Col<Player, float>(tableName, "health");
            MaxHealth = new global::SpacetimeDB.Col<Player, float>(tableName, "max_health");
            Stamina = new global::SpacetimeDB.Col<Player, float>(tableName, "stamina");
            MaxStamina = new global::SpacetimeDB.Col<Player, float>(tableName, "max_stamina");
            IsOnline = new global::SpacetimeDB.Col<Player, bool>(tableName, "is_online");
        }
    }

    public sealed class PlayerIxCols
    {
        public global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity> Identity { get; }

        public PlayerIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity>(tableName, "identity");
        }
    }
}
