// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SlotSessionHandle : RemoteTableHandle<EventContext, SlotSession>
        {
            protected override string RemoteTableName => "slot_session";

            public sealed class MachineIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(SlotSession row) => row.MachineId;

                public MachineIdUniqueIndex(SlotSessionHandle table) : base(table) { }
            }

            public readonly MachineIdUniqueIndex MachineId;

            internal SlotSessionHandle(DbConnection conn) : base(conn)
            {
                MachineId = new(this);
            }

            protected override object GetPrimaryKey(SlotSession row) => row.MachineId;
        }

        public readonly SlotSessionHandle SlotSession;
    }

    public sealed class SlotSessionCols
    {
        public global::SpacetimeDB.Col<SlotSession, ulong> MachineId { get; }
        public global::SpacetimeDB.Col<SlotSession, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.Col<SlotSession, string> Reels { get; }
        public global::SpacetimeDB.Col<SlotSession, bool> IsIdle { get; }
        public global::SpacetimeDB.Col<SlotSession, ulong> Bet { get; }
        public global::SpacetimeDB.Col<SlotSession, ulong> WinAmount { get; }
        public global::SpacetimeDB.Col<SlotSession, ulong> ExpiresAt { get; }

        public SlotSessionCols(string tableName)
        {
            MachineId = new global::SpacetimeDB.Col<SlotSession, ulong>(tableName, "machine_id");
            PlayerId = new global::SpacetimeDB.Col<SlotSession, SpacetimeDB.Identity>(tableName, "player_id");
            Reels = new global::SpacetimeDB.Col<SlotSession, string>(tableName, "reels");
            IsIdle = new global::SpacetimeDB.Col<SlotSession, bool>(tableName, "is_idle");
            Bet = new global::SpacetimeDB.Col<SlotSession, ulong>(tableName, "bet");
            WinAmount = new global::SpacetimeDB.Col<SlotSession, ulong>(tableName, "win_amount");
            ExpiresAt = new global::SpacetimeDB.Col<SlotSession, ulong>(tableName, "expires_at");
        }
    }

    public sealed class SlotSessionIxCols
    {
        public global::SpacetimeDB.IxCol<SlotSession, ulong> MachineId { get; }

        public SlotSessionIxCols(string tableName)
        {
            MachineId = new global::SpacetimeDB.IxCol<SlotSession, ulong>(tableName, "machine_id");
        }
    }
}
