// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WorldItemHandle : RemoteTableHandle<EventContext, WorldItem>
        {
            protected override string RemoteTableName => "world_item";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(WorldItem row) => row.Id;

                public IdUniqueIndex(WorldItemHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal WorldItemHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(WorldItem row) => row.Id;
        }

        public readonly WorldItemHandle WorldItem;
    }

    public sealed class WorldItemCols
    {
        public global::SpacetimeDB.Col<WorldItem, ulong> Id { get; }
        public global::SpacetimeDB.Col<WorldItem, string> ItemType { get; }
        public global::SpacetimeDB.Col<WorldItem, uint> Quantity { get; }
        public global::SpacetimeDB.Col<WorldItem, float> PosX { get; }
        public global::SpacetimeDB.Col<WorldItem, float> PosY { get; }
        public global::SpacetimeDB.Col<WorldItem, float> PosZ { get; }

        public WorldItemCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<WorldItem, ulong>(tableName, "id");
            ItemType = new global::SpacetimeDB.Col<WorldItem, string>(tableName, "item_type");
            Quantity = new global::SpacetimeDB.Col<WorldItem, uint>(tableName, "quantity");
            PosX = new global::SpacetimeDB.Col<WorldItem, float>(tableName, "pos_x");
            PosY = new global::SpacetimeDB.Col<WorldItem, float>(tableName, "pos_y");
            PosZ = new global::SpacetimeDB.Col<WorldItem, float>(tableName, "pos_z");
        }
    }

    public sealed class WorldItemIxCols
    {
        public global::SpacetimeDB.IxCol<WorldItem, ulong> Id { get; }

        public WorldItemIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<WorldItem, ulong>(tableName, "id");
        }
    }
}
