// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AccessControl
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "entity_table")]
        public string EntityTable;
        [DataMember(Name = "owner_id")]
        public SpacetimeDB.Identity OwnerId;
        [DataMember(Name = "is_public")]
        public bool IsPublic;

        public AccessControl(
            ulong Id,
            ulong EntityId,
            string EntityTable,
            SpacetimeDB.Identity OwnerId,
            bool IsPublic
        )
        {
            this.Id = Id;
            this.EntityId = EntityId;
            this.EntityTable = EntityTable;
            this.OwnerId = OwnerId;
            this.IsPublic = IsPublic;
        }

        public AccessControl()
        {
            this.EntityTable = "";
        }
    }
}
