// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ArcadeSession
    {
        [DataMember(Name = "machine_id")]
        public ulong MachineId;
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "game_type")]
        public byte GameType;
        [DataMember(Name = "state")]
        public byte State;
        [DataMember(Name = "bet")]
        public ulong Bet;
        [DataMember(Name = "challenge_data")]
        public string ChallengeData;
        [DataMember(Name = "start_time")]
        public ulong StartTime;
        [DataMember(Name = "expires_at")]
        public ulong ExpiresAt;

        public ArcadeSession(
            ulong MachineId,
            SpacetimeDB.Identity PlayerId,
            byte GameType,
            byte State,
            ulong Bet,
            string ChallengeData,
            ulong StartTime,
            ulong ExpiresAt
        )
        {
            this.MachineId = MachineId;
            this.PlayerId = PlayerId;
            this.GameType = GameType;
            this.State = State;
            this.Bet = Bet;
            this.ChallengeData = ChallengeData;
            this.StartTime = StartTime;
            this.ExpiresAt = ExpiresAt;
        }

        public ArcadeSession()
        {
            this.ChallengeData = "";
        }
    }
}
