// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BlackjackSeat
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "machine_id")]
        public ulong MachineId;
        [DataMember(Name = "seat_index")]
        public byte SeatIndex;
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "hand")]
        public string Hand;
        [DataMember(Name = "bet")]
        public ulong Bet;
        [DataMember(Name = "state")]
        public byte State;
        [DataMember(Name = "round_id")]
        public uint RoundId;

        public BlackjackSeat(
            ulong Id,
            ulong MachineId,
            byte SeatIndex,
            SpacetimeDB.Identity PlayerId,
            string Hand,
            ulong Bet,
            byte State,
            uint RoundId
        )
        {
            this.Id = Id;
            this.MachineId = MachineId;
            this.SeatIndex = SeatIndex;
            this.PlayerId = PlayerId;
            this.Hand = Hand;
            this.Bet = Bet;
            this.State = State;
            this.RoundId = RoundId;
        }

        public BlackjackSeat()
        {
            this.Hand = "";
        }
    }
}
