// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BlackjackGame
    {
        [DataMember(Name = "machine_id")]
        public ulong MachineId;
        [DataMember(Name = "state")]
        public byte State;
        [DataMember(Name = "dealer_hand")]
        public string DealerHand;
        [DataMember(Name = "dealer_hand_hidden")]
        public string DealerHandHidden;
        [DataMember(Name = "deck")]
        public string Deck;
        [DataMember(Name = "round_id")]
        public uint RoundId;

        public BlackjackGame(
            ulong MachineId,
            byte State,
            string DealerHand,
            string DealerHandHidden,
            string Deck,
            uint RoundId
        )
        {
            this.MachineId = MachineId;
            this.State = State;
            this.DealerHand = DealerHand;
            this.DealerHandHidden = DealerHandHidden;
            this.Deck = Deck;
            this.RoundId = RoundId;
        }

        public BlackjackGame()
        {
            this.DealerHand = "";
            this.DealerHandHidden = "";
            this.Deck = "";
        }
    }
}
