// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CoinPusherState
    {
        [DataMember(Name = "machine_id")]
        public ulong MachineId;
        [DataMember(Name = "coin_count")]
        public uint CoinCount;
        [DataMember(Name = "copper_pool")]
        public ulong CopperPool;
        [DataMember(Name = "last_pusher_id")]
        public SpacetimeDB.Identity LastPusherId;
        [DataMember(Name = "last_push_time")]
        public ulong LastPushTime;
        [DataMember(Name = "jackpot_threshold")]
        public uint JackpotThreshold;

        public CoinPusherState(
            ulong MachineId,
            uint CoinCount,
            ulong CopperPool,
            SpacetimeDB.Identity LastPusherId,
            ulong LastPushTime,
            uint JackpotThreshold
        )
        {
            this.MachineId = MachineId;
            this.CoinCount = CoinCount;
            this.CopperPool = CopperPool;
            this.LastPusherId = LastPusherId;
            this.LastPushTime = LastPushTime;
            this.JackpotThreshold = JackpotThreshold;
        }

        public CoinPusherState()
        {
        }
    }
}
