// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ContainerSlot
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "container_id")]
        public ulong ContainerId;
        [DataMember(Name = "container_table")]
        public string ContainerTable;
        [DataMember(Name = "slot")]
        public int Slot;
        [DataMember(Name = "item_type")]
        public string ItemType;
        [DataMember(Name = "quantity")]
        public uint Quantity;

        public ContainerSlot(
            ulong Id,
            ulong ContainerId,
            string ContainerTable,
            int Slot,
            string ItemType,
            uint Quantity
        )
        {
            this.Id = Id;
            this.ContainerId = ContainerId;
            this.ContainerTable = ContainerTable;
            this.Slot = Slot;
            this.ItemType = ItemType;
            this.Quantity = Quantity;
        }

        public ContainerSlot()
        {
            this.ContainerTable = "";
            this.ItemType = "";
        }
    }
}
