// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CraftingRecipe
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "result_item_type")]
        public string ResultItemType;
        [DataMember(Name = "result_quantity")]
        public uint ResultQuantity;
        [DataMember(Name = "ingredients")]
        public string Ingredients;
        [DataMember(Name = "craft_time_seconds")]
        public float CraftTimeSeconds;

        public CraftingRecipe(
            ulong Id,
            string ResultItemType,
            uint ResultQuantity,
            string Ingredients,
            float CraftTimeSeconds
        )
        {
            this.Id = Id;
            this.ResultItemType = ResultItemType;
            this.ResultQuantity = ResultQuantity;
            this.Ingredients = Ingredients;
            this.CraftTimeSeconds = CraftTimeSeconds;
        }

        public CraftingRecipe()
        {
            this.ResultItemType = "";
            this.Ingredients = "";
        }
    }
}
