// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CurrencyTransaction
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "amount")]
        public long Amount;
        [DataMember(Name = "reason")]
        public string Reason;
        [DataMember(Name = "timestamp")]
        public ulong Timestamp;

        public CurrencyTransaction(
            ulong Id,
            SpacetimeDB.Identity PlayerId,
            long Amount,
            string Reason,
            ulong Timestamp
        )
        {
            this.Id = Id;
            this.PlayerId = PlayerId;
            this.Amount = Amount;
            this.Reason = Reason;
            this.Timestamp = Timestamp;
        }

        public CurrencyTransaction()
        {
            this.Reason = "";
        }
    }
}
