// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CurrencyBalance
    {
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "copper")]
        public ulong Copper;

        public CurrencyBalance(
            SpacetimeDB.Identity PlayerId,
            ulong Copper
        )
        {
            this.PlayerId = PlayerId;
            this.Copper = Copper;
        }

        public CurrencyBalance()
        {
        }
    }
}
