// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DamageEvent
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "source_id")]
        public ulong SourceId;
        [DataMember(Name = "source_type")]
        public string SourceType;
        [DataMember(Name = "target_id")]
        public ulong TargetId;
        [DataMember(Name = "target_type")]
        public string TargetType;
        [DataMember(Name = "amount")]
        public int Amount;
        [DataMember(Name = "damage_type")]
        public string DamageType;
        [DataMember(Name = "timestamp")]
        public ulong Timestamp;

        public DamageEvent(
            ulong Id,
            ulong SourceId,
            string SourceType,
            ulong TargetId,
            string TargetType,
            int Amount,
            string DamageType,
            ulong Timestamp
        )
        {
            this.Id = Id;
            this.SourceId = SourceId;
            this.SourceType = SourceType;
            this.TargetId = TargetId;
            this.TargetType = TargetType;
            this.Amount = Amount;
            this.DamageType = DamageType;
            this.Timestamp = Timestamp;
        }

        public DamageEvent()
        {
            this.SourceType = "";
            this.TargetType = "";
            this.DamageType = "";
        }
    }
}
