// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class FurnaceState
    {
        [DataMember(Name = "structure_id")]
        public ulong StructureId;
        [DataMember(Name = "recipe_type")]
        public string RecipeType;
        [DataMember(Name = "start_time_ms")]
        public ulong StartTimeMs;
        [DataMember(Name = "duration_ms")]
        public ulong DurationMs;
        [DataMember(Name = "complete")]
        public bool Complete;

        public FurnaceState(
            ulong StructureId,
            string RecipeType,
            ulong StartTimeMs,
            ulong DurationMs,
            bool Complete
        )
        {
            this.StructureId = StructureId;
            this.RecipeType = RecipeType;
            this.StartTimeMs = StartTimeMs;
            this.DurationMs = DurationMs;
            this.Complete = Complete;
        }

        public FurnaceState()
        {
            this.RecipeType = "";
        }
    }
}
