// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class InventoryItem
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "owner_id")]
        public SpacetimeDB.Identity OwnerId;
        [DataMember(Name = "item_type")]
        public string ItemType;
        [DataMember(Name = "quantity")]
        public uint Quantity;
        [DataMember(Name = "slot")]
        public int Slot;

        public InventoryItem(
            ulong Id,
            SpacetimeDB.Identity OwnerId,
            string ItemType,
            uint Quantity,
            int Slot
        )
        {
            this.Id = Id;
            this.OwnerId = OwnerId;
            this.ItemType = ItemType;
            this.Quantity = Quantity;
            this.Slot = Slot;
        }

        public InventoryItem()
        {
            this.ItemType = "";
        }
    }
}
