// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ModConfig
    {
        [DataMember(Name = "mod_id")]
        public string ModId;
        [DataMember(Name = "enabled")]
        public bool Enabled;
        [DataMember(Name = "version")]
        public string Version;
        [DataMember(Name = "dependencies")]
        public string Dependencies;

        public ModConfig(
            string ModId,
            bool Enabled,
            string Version,
            string Dependencies
        )
        {
            this.ModId = ModId;
            this.Enabled = Enabled;
            this.Version = Version;
            this.Dependencies = Dependencies;
        }

        public ModConfig()
        {
            this.ModId = "";
            this.Version = "";
            this.Dependencies = "";
        }
    }
}
