// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Npc
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "npc_type")]
        public string NpcType;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_y")]
        public float PosY;
        [DataMember(Name = "pos_z")]
        public float PosZ;
        [DataMember(Name = "rot_y")]
        public float RotY;
        [DataMember(Name = "health")]
        public int Health;
        [DataMember(Name = "max_health")]
        public int MaxHealth;
        [DataMember(Name = "current_state")]
        public string CurrentState;
        [DataMember(Name = "target_entity_id")]
        public ulong TargetEntityId;
        [DataMember(Name = "target_entity_type")]
        public string TargetEntityType;
        [DataMember(Name = "spawn_pos_x")]
        public float SpawnPosX;
        [DataMember(Name = "spawn_pos_y")]
        public float SpawnPosY;
        [DataMember(Name = "spawn_pos_z")]
        public float SpawnPosZ;
        [DataMember(Name = "is_alive")]
        public bool IsAlive;
        [DataMember(Name = "last_update_ms")]
        public ulong LastUpdateMs;

        public Npc(
            ulong Id,
            string NpcType,
            float PosX,
            float PosY,
            float PosZ,
            float RotY,
            int Health,
            int MaxHealth,
            string CurrentState,
            ulong TargetEntityId,
            string TargetEntityType,
            float SpawnPosX,
            float SpawnPosY,
            float SpawnPosZ,
            bool IsAlive,
            ulong LastUpdateMs
        )
        {
            this.Id = Id;
            this.NpcType = NpcType;
            this.PosX = PosX;
            this.PosY = PosY;
            this.PosZ = PosZ;
            this.RotY = RotY;
            this.Health = Health;
            this.MaxHealth = MaxHealth;
            this.CurrentState = CurrentState;
            this.TargetEntityId = TargetEntityId;
            this.TargetEntityType = TargetEntityType;
            this.SpawnPosX = SpawnPosX;
            this.SpawnPosY = SpawnPosY;
            this.SpawnPosZ = SpawnPosZ;
            this.IsAlive = IsAlive;
            this.LastUpdateMs = LastUpdateMs;
        }

        public Npc()
        {
            this.NpcType = "";
            this.CurrentState = "";
            this.TargetEntityType = "";
        }
    }
}
