// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NpcLootTable
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "npc_type")]
        public string NpcType;
        [DataMember(Name = "item_type")]
        public string ItemType;
        [DataMember(Name = "quantity")]
        public int Quantity;
        [DataMember(Name = "drop_chance")]
        public float DropChance;

        public NpcLootTable(
            ulong Id,
            string NpcType,
            string ItemType,
            int Quantity,
            float DropChance
        )
        {
            this.Id = Id;
            this.NpcType = NpcType;
            this.ItemType = ItemType;
            this.Quantity = Quantity;
            this.DropChance = DropChance;
        }

        public NpcLootTable()
        {
            this.NpcType = "";
            this.ItemType = "";
        }
    }
}
