// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NpcSpawnRule
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "npc_type")]
        public string NpcType;
        [DataMember(Name = "zone_x")]
        public float ZoneX;
        [DataMember(Name = "zone_z")]
        public float ZoneZ;
        [DataMember(Name = "zone_radius")]
        public float ZoneRadius;
        [DataMember(Name = "max_count")]
        public int MaxCount;
        [DataMember(Name = "respawn_time_sec")]
        public float RespawnTimeSec;

        public NpcSpawnRule(
            ulong Id,
            string NpcType,
            float ZoneX,
            float ZoneZ,
            float ZoneRadius,
            int MaxCount,
            float RespawnTimeSec
        )
        {
            this.Id = Id;
            this.NpcType = NpcType;
            this.ZoneX = ZoneX;
            this.ZoneZ = ZoneZ;
            this.ZoneRadius = ZoneRadius;
            this.MaxCount = MaxCount;
            this.RespawnTimeSec = RespawnTimeSec;
        }

        public NpcSpawnRule()
        {
            this.NpcType = "";
        }
    }
}
