// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NpcTradeOffer
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "npc_type")]
        public string NpcType;
        [DataMember(Name = "item_type")]
        public string ItemType;
        [DataMember(Name = "price")]
        public int Price;
        [DataMember(Name = "currency")]
        public string Currency;

        public NpcTradeOffer(
            ulong Id,
            string NpcType,
            string ItemType,
            int Price,
            string Currency
        )
        {
            this.Id = Id;
            this.NpcType = NpcType;
            this.ItemType = ItemType;
            this.Price = Price;
            this.Currency = Currency;
        }

        public NpcTradeOffer()
        {
            this.NpcType = "";
            this.ItemType = "";
            this.Currency = "";
        }
    }
}
