// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_y")]
        public float PosY;
        [DataMember(Name = "pos_z")]
        public float PosZ;
        [DataMember(Name = "rot_y")]
        public float RotY;
        [DataMember(Name = "health")]
        public float Health;
        [DataMember(Name = "max_health")]
        public float MaxHealth;
        [DataMember(Name = "stamina")]
        public float Stamina;
        [DataMember(Name = "max_stamina")]
        public float MaxStamina;
        [DataMember(Name = "is_online")]
        public bool IsOnline;

        public Player(
            SpacetimeDB.Identity Identity,
            string Name,
            float PosX,
            float PosY,
            float PosZ,
            float RotY,
            float Health,
            float MaxHealth,
            float Stamina,
            float MaxStamina,
            bool IsOnline
        )
        {
            this.Identity = Identity;
            this.Name = Name;
            this.PosX = PosX;
            this.PosY = PosY;
            this.PosZ = PosZ;
            this.RotY = RotY;
            this.Health = Health;
            this.MaxHealth = MaxHealth;
            this.Stamina = Stamina;
            this.MaxStamina = MaxStamina;
            this.IsOnline = IsOnline;
        }

        public Player()
        {
            this.Name = "";
        }
    }
}
