// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SignText
    {
        [DataMember(Name = "structure_id")]
        public ulong StructureId;
        [DataMember(Name = "text")]
        public string Text;

        public SignText(
            ulong StructureId,
            string Text
        )
        {
            this.StructureId = StructureId;
            this.Text = Text;
        }

        public SignText()
        {
            this.Text = "";
        }
    }
}
