// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SlotSession
    {
        [DataMember(Name = "machine_id")]
        public ulong MachineId;
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "reels")]
        public string Reels;
        [DataMember(Name = "is_idle")]
        public bool IsIdle;
        [DataMember(Name = "bet")]
        public ulong Bet;
        [DataMember(Name = "win_amount")]
        public ulong WinAmount;
        [DataMember(Name = "expires_at")]
        public ulong ExpiresAt;

        public SlotSession(
            ulong MachineId,
            SpacetimeDB.Identity PlayerId,
            string Reels,
            bool IsIdle,
            ulong Bet,
            ulong WinAmount,
            ulong ExpiresAt
        )
        {
            this.MachineId = MachineId;
            this.PlayerId = PlayerId;
            this.Reels = Reels;
            this.IsIdle = IsIdle;
            this.Bet = Bet;
            this.WinAmount = WinAmount;
            this.ExpiresAt = ExpiresAt;
        }

        public SlotSession()
        {
            this.Reels = "";
        }
    }
}
