// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldObject
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "object_type")]
        public string ObjectType;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_y")]
        public float PosY;
        [DataMember(Name = "pos_z")]
        public float PosZ;
        [DataMember(Name = "rot_y")]
        public float RotY;
        [DataMember(Name = "health")]
        public uint Health;
        [DataMember(Name = "max_health")]
        public uint MaxHealth;

        public WorldObject(
            ulong Id,
            string ObjectType,
            float PosX,
            float PosY,
            float PosZ,
            float RotY,
            uint Health,
            uint MaxHealth
        )
        {
            this.Id = Id;
            this.ObjectType = ObjectType;
            this.PosX = PosX;
            this.PosY = PosY;
            this.PosZ = PosZ;
            this.RotY = RotY;
            this.Health = Health;
            this.MaxHealth = MaxHealth;
        }

        public WorldObject()
        {
            this.ObjectType = "";
        }
    }
}
