// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldItem
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "item_type")]
        public string ItemType;
        [DataMember(Name = "quantity")]
        public uint Quantity;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_y")]
        public float PosY;
        [DataMember(Name = "pos_z")]
        public float PosZ;

        public WorldItem(
            ulong Id,
            string ItemType,
            uint Quantity,
            float PosX,
            float PosY,
            float PosZ
        )
        {
            this.Id = Id;
            this.ItemType = ItemType;
            this.Quantity = Quantity;
            this.PosX = PosX;
            this.PosY = PosY;
            this.PosZ = PosZ;
        }

        public WorldItem()
        {
            this.ItemType = "";
        }
    }
}
