// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class FurnaceStateHandle : RemoteTableHandle<EventContext, FurnaceState>
        {
            protected override string RemoteTableName => "furnace_state";

            public sealed class StructureIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(FurnaceState row) => row.StructureId;

                public StructureIdUniqueIndex(FurnaceStateHandle table) : base(table) { }
            }

            public readonly StructureIdUniqueIndex StructureId;

            internal FurnaceStateHandle(DbConnection conn) : base(conn)
            {
                StructureId = new(this);
            }

            protected override object GetPrimaryKey(FurnaceState row) => row.StructureId;
        }

        public readonly FurnaceStateHandle FurnaceState;
    }

    public sealed class FurnaceStateCols
    {
        public global::SpacetimeDB.Col<FurnaceState, ulong> StructureId { get; }
        public global::SpacetimeDB.Col<FurnaceState, string> RecipeType { get; }
        public global::SpacetimeDB.Col<FurnaceState, ulong> StartTimeMs { get; }
        public global::SpacetimeDB.Col<FurnaceState, ulong> DurationMs { get; }
        public global::SpacetimeDB.Col<FurnaceState, bool> Complete { get; }

        public FurnaceStateCols(string tableName)
        {
            StructureId = new global::SpacetimeDB.Col<FurnaceState, ulong>(tableName, "structure_id");
            RecipeType = new global::SpacetimeDB.Col<FurnaceState, string>(tableName, "recipe_type");
            StartTimeMs = new global::SpacetimeDB.Col<FurnaceState, ulong>(tableName, "start_time_ms");
            DurationMs = new global::SpacetimeDB.Col<FurnaceState, ulong>(tableName, "duration_ms");
            Complete = new global::SpacetimeDB.Col<FurnaceState, bool>(tableName, "complete");
        }
    }

    public sealed class FurnaceStateIxCols
    {
        public global::SpacetimeDB.IxCol<FurnaceState, ulong> StructureId { get; }

        public FurnaceStateIxCols(string tableName)
        {
            StructureId = new global::SpacetimeDB.IxCol<FurnaceState, ulong>(tableName, "structure_id");
        }
    }
}
