// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class InventoryItemHandle : RemoteTableHandle<EventContext, InventoryItem>
        {
            protected override string RemoteTableName => "inventory_item";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(InventoryItem row) => row.Id;

                public IdUniqueIndex(InventoryItemHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal InventoryItemHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(InventoryItem row) => row.Id;
        }

        public readonly InventoryItemHandle InventoryItem;
    }

    public sealed class InventoryItemCols
    {
        public global::SpacetimeDB.Col<InventoryItem, ulong> Id { get; }
        public global::SpacetimeDB.Col<InventoryItem, SpacetimeDB.Identity> OwnerId { get; }
        public global::SpacetimeDB.Col<InventoryItem, string> ItemType { get; }
        public global::SpacetimeDB.Col<InventoryItem, uint> Quantity { get; }
        public global::SpacetimeDB.Col<InventoryItem, int> Slot { get; }

        public InventoryItemCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<InventoryItem, ulong>(tableName, "id");
            OwnerId = new global::SpacetimeDB.Col<InventoryItem, SpacetimeDB.Identity>(tableName, "owner_id");
            ItemType = new global::SpacetimeDB.Col<InventoryItem, string>(tableName, "item_type");
            Quantity = new global::SpacetimeDB.Col<InventoryItem, uint>(tableName, "quantity");
            Slot = new global::SpacetimeDB.Col<InventoryItem, int>(tableName, "slot");
        }
    }

    public sealed class InventoryItemIxCols
    {
        public global::SpacetimeDB.IxCol<InventoryItem, ulong> Id { get; }

        public InventoryItemIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<InventoryItem, ulong>(tableName, "id");
        }
    }
}
