// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NpcHandle : RemoteTableHandle<EventContext, Npc>
        {
            protected override string RemoteTableName => "npc";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Npc row) => row.Id;

                public IdUniqueIndex(NpcHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal NpcHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Npc row) => row.Id;
        }

        public readonly NpcHandle Npc;
    }

    public sealed class NpcCols
    {
        public global::SpacetimeDB.Col<Npc, ulong> Id { get; }
        public global::SpacetimeDB.Col<Npc, string> NpcType { get; }
        public global::SpacetimeDB.Col<Npc, float> PosX { get; }
        public global::SpacetimeDB.Col<Npc, float> PosY { get; }
        public global::SpacetimeDB.Col<Npc, float> PosZ { get; }
        public global::SpacetimeDB.Col<Npc, float> RotY { get; }
        public global::SpacetimeDB.Col<Npc, int> Health { get; }
        public global::SpacetimeDB.Col<Npc, int> MaxHealth { get; }
        public global::SpacetimeDB.Col<Npc, string> CurrentState { get; }
        public global::SpacetimeDB.Col<Npc, ulong> TargetEntityId { get; }
        public global::SpacetimeDB.Col<Npc, string> TargetEntityType { get; }
        public global::SpacetimeDB.Col<Npc, float> SpawnPosX { get; }
        public global::SpacetimeDB.Col<Npc, float> SpawnPosY { get; }
        public global::SpacetimeDB.Col<Npc, float> SpawnPosZ { get; }
        public global::SpacetimeDB.Col<Npc, bool> IsAlive { get; }
        public global::SpacetimeDB.Col<Npc, ulong> LastUpdateMs { get; }

        public NpcCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Npc, ulong>(tableName, "id");
            NpcType = new global::SpacetimeDB.Col<Npc, string>(tableName, "npc_type");
            PosX = new global::SpacetimeDB.Col<Npc, float>(tableName, "pos_x");
            PosY = new global::SpacetimeDB.Col<Npc, float>(tableName, "pos_y");
            PosZ = new global::SpacetimeDB.Col<Npc, float>(tableName, "pos_z");
            RotY = new global::SpacetimeDB.Col<Npc, float>(tableName, "rot_y");
            Health = new global::SpacetimeDB.Col<Npc, int>(tableName, "health");
            MaxHealth = new global::SpacetimeDB.Col<Npc, int>(tableName, "max_health");
            CurrentState = new global::SpacetimeDB.Col<Npc, string>(tableName, "current_state");
            TargetEntityId = new global::SpacetimeDB.Col<Npc, ulong>(tableName, "target_entity_id");
            TargetEntityType = new global::SpacetimeDB.Col<Npc, string>(tableName, "target_entity_type");
            SpawnPosX = new global::SpacetimeDB.Col<Npc, float>(tableName, "spawn_pos_x");
            SpawnPosY = new global::SpacetimeDB.Col<Npc, float>(tableName, "spawn_pos_y");
            SpawnPosZ = new global::SpacetimeDB.Col<Npc, float>(tableName, "spawn_pos_z");
            IsAlive = new global::SpacetimeDB.Col<Npc, bool>(tableName, "is_alive");
            LastUpdateMs = new global::SpacetimeDB.Col<Npc, ulong>(tableName, "last_update_ms");
        }
    }

    public sealed class NpcIxCols
    {
        public global::SpacetimeDB.IxCol<Npc, ulong> Id { get; }

        public NpcIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Npc, ulong>(tableName, "id");
        }
    }
}
