// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NpcConfigHandle : RemoteTableHandle<EventContext, NpcConfig>
        {
            protected override string RemoteTableName => "npc_config";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(NpcConfig row) => row.Id;

                public IdUniqueIndex(NpcConfigHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal NpcConfigHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(NpcConfig row) => row.Id;
        }

        public readonly NpcConfigHandle NpcConfig;
    }

    public sealed class NpcConfigCols
    {
        public global::SpacetimeDB.Col<NpcConfig, ulong> Id { get; }
        public global::SpacetimeDB.Col<NpcConfig, string> NpcType { get; }
        public global::SpacetimeDB.Col<NpcConfig, int> MaxHealth { get; }
        public global::SpacetimeDB.Col<NpcConfig, int> AttackDamage { get; }
        public global::SpacetimeDB.Col<NpcConfig, float> AttackRange { get; }
        public global::SpacetimeDB.Col<NpcConfig, ulong> AttackCooldownMs { get; }
        public global::SpacetimeDB.Col<NpcConfig, bool> IsAttackable { get; }
        public global::SpacetimeDB.Col<NpcConfig, bool> IsTrader { get; }
        public global::SpacetimeDB.Col<NpcConfig, bool> HasDialogue { get; }

        public NpcConfigCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<NpcConfig, ulong>(tableName, "id");
            NpcType = new global::SpacetimeDB.Col<NpcConfig, string>(tableName, "npc_type");
            MaxHealth = new global::SpacetimeDB.Col<NpcConfig, int>(tableName, "max_health");
            AttackDamage = new global::SpacetimeDB.Col<NpcConfig, int>(tableName, "attack_damage");
            AttackRange = new global::SpacetimeDB.Col<NpcConfig, float>(tableName, "attack_range");
            AttackCooldownMs = new global::SpacetimeDB.Col<NpcConfig, ulong>(tableName, "attack_cooldown_ms");
            IsAttackable = new global::SpacetimeDB.Col<NpcConfig, bool>(tableName, "is_attackable");
            IsTrader = new global::SpacetimeDB.Col<NpcConfig, bool>(tableName, "is_trader");
            HasDialogue = new global::SpacetimeDB.Col<NpcConfig, bool>(tableName, "has_dialogue");
        }
    }

    public sealed class NpcConfigIxCols
    {
        public global::SpacetimeDB.IxCol<NpcConfig, ulong> Id { get; }

        public NpcConfigIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<NpcConfig, ulong>(tableName, "id");
        }
    }
}
