// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NpcLootTableHandle : RemoteTableHandle<EventContext, NpcLootTable>
        {
            protected override string RemoteTableName => "npc_loot_table";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(NpcLootTable row) => row.Id;

                public IdUniqueIndex(NpcLootTableHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal NpcLootTableHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(NpcLootTable row) => row.Id;
        }

        public readonly NpcLootTableHandle NpcLootTable;
    }

    public sealed class NpcLootTableCols
    {
        public global::SpacetimeDB.Col<NpcLootTable, ulong> Id { get; }
        public global::SpacetimeDB.Col<NpcLootTable, string> NpcType { get; }
        public global::SpacetimeDB.Col<NpcLootTable, string> ItemType { get; }
        public global::SpacetimeDB.Col<NpcLootTable, int> Quantity { get; }
        public global::SpacetimeDB.Col<NpcLootTable, float> DropChance { get; }

        public NpcLootTableCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<NpcLootTable, ulong>(tableName, "id");
            NpcType = new global::SpacetimeDB.Col<NpcLootTable, string>(tableName, "npc_type");
            ItemType = new global::SpacetimeDB.Col<NpcLootTable, string>(tableName, "item_type");
            Quantity = new global::SpacetimeDB.Col<NpcLootTable, int>(tableName, "quantity");
            DropChance = new global::SpacetimeDB.Col<NpcLootTable, float>(tableName, "drop_chance");
        }
    }

    public sealed class NpcLootTableIxCols
    {
        public global::SpacetimeDB.IxCol<NpcLootTable, ulong> Id { get; }

        public NpcLootTableIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<NpcLootTable, ulong>(tableName, "id");
        }
    }
}
