// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NpcTradeOfferHandle : RemoteTableHandle<EventContext, NpcTradeOffer>
        {
            protected override string RemoteTableName => "npc_trade_offer";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(NpcTradeOffer row) => row.Id;

                public IdUniqueIndex(NpcTradeOfferHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal NpcTradeOfferHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(NpcTradeOffer row) => row.Id;
        }

        public readonly NpcTradeOfferHandle NpcTradeOffer;
    }

    public sealed class NpcTradeOfferCols
    {
        public global::SpacetimeDB.Col<NpcTradeOffer, ulong> Id { get; }
        public global::SpacetimeDB.Col<NpcTradeOffer, string> NpcType { get; }
        public global::SpacetimeDB.Col<NpcTradeOffer, string> ItemType { get; }
        public global::SpacetimeDB.Col<NpcTradeOffer, int> Price { get; }
        public global::SpacetimeDB.Col<NpcTradeOffer, string> Currency { get; }

        public NpcTradeOfferCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<NpcTradeOffer, ulong>(tableName, "id");
            NpcType = new global::SpacetimeDB.Col<NpcTradeOffer, string>(tableName, "npc_type");
            ItemType = new global::SpacetimeDB.Col<NpcTradeOffer, string>(tableName, "item_type");
            Price = new global::SpacetimeDB.Col<NpcTradeOffer, int>(tableName, "price");
            Currency = new global::SpacetimeDB.Col<NpcTradeOffer, string>(tableName, "currency");
        }
    }

    public sealed class NpcTradeOfferIxCols
    {
        public global::SpacetimeDB.IxCol<NpcTradeOffer, ulong> Id { get; }

        public NpcTradeOfferIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<NpcTradeOffer, ulong>(tableName, "id");
        }
    }
}
