// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlacedStructureHandle : RemoteTableHandle<EventContext, PlacedStructure>
        {
            protected override string RemoteTableName => "placed_structure";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlacedStructure row) => row.Id;

                public IdUniqueIndex(PlacedStructureHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal PlacedStructureHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(PlacedStructure row) => row.Id;
        }

        public readonly PlacedStructureHandle PlacedStructure;
    }

    public sealed class PlacedStructureCols
    {
        public global::SpacetimeDB.Col<PlacedStructure, ulong> Id { get; }
        public global::SpacetimeDB.Col<PlacedStructure, SpacetimeDB.Identity> OwnerId { get; }
        public global::SpacetimeDB.Col<PlacedStructure, string> StructureType { get; }
        public global::SpacetimeDB.Col<PlacedStructure, float> PosX { get; }
        public global::SpacetimeDB.Col<PlacedStructure, float> PosY { get; }
        public global::SpacetimeDB.Col<PlacedStructure, float> PosZ { get; }
        public global::SpacetimeDB.Col<PlacedStructure, float> RotY { get; }
        public global::SpacetimeDB.Col<PlacedStructure, float> Health { get; }
        public global::SpacetimeDB.Col<PlacedStructure, float> MaxHealth { get; }

        public PlacedStructureCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<PlacedStructure, ulong>(tableName, "id");
            OwnerId = new global::SpacetimeDB.Col<PlacedStructure, SpacetimeDB.Identity>(tableName, "owner_id");
            StructureType = new global::SpacetimeDB.Col<PlacedStructure, string>(tableName, "structure_type");
            PosX = new global::SpacetimeDB.Col<PlacedStructure, float>(tableName, "pos_x");
            PosY = new global::SpacetimeDB.Col<PlacedStructure, float>(tableName, "pos_y");
            PosZ = new global::SpacetimeDB.Col<PlacedStructure, float>(tableName, "pos_z");
            RotY = new global::SpacetimeDB.Col<PlacedStructure, float>(tableName, "rot_y");
            Health = new global::SpacetimeDB.Col<PlacedStructure, float>(tableName, "health");
            MaxHealth = new global::SpacetimeDB.Col<PlacedStructure, float>(tableName, "max_health");
        }
    }

    public sealed class PlacedStructureIxCols
    {
        public global::SpacetimeDB.IxCol<PlacedStructure, ulong> Id { get; }

        public PlacedStructureIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<PlacedStructure, ulong>(tableName, "id");
        }
    }
}
