// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ServiceIdentityHandle : RemoteTableHandle<EventContext, ServiceIdentity>
        {
            protected override string RemoteTableName => "service_identity";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ServiceIdentity row) => row.Id;

                public IdUniqueIndex(ServiceIdentityHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ServiceIdentityHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ServiceIdentity row) => row.Id;
        }

        public readonly ServiceIdentityHandle ServiceIdentity;
    }

    public sealed class ServiceIdentityCols
    {
        public global::SpacetimeDB.Col<ServiceIdentity, ulong> Id { get; }
        public global::SpacetimeDB.Col<ServiceIdentity, SpacetimeDB.Identity> ServiceId { get; }

        public ServiceIdentityCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ServiceIdentity, ulong>(tableName, "id");
            ServiceId = new global::SpacetimeDB.Col<ServiceIdentity, SpacetimeDB.Identity>(tableName, "service_id");
        }
    }

    public sealed class ServiceIdentityIxCols
    {
        public global::SpacetimeDB.IxCol<ServiceIdentity, ulong> Id { get; }

        public ServiceIdentityIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ServiceIdentity, ulong>(tableName, "id");
        }
    }
}
