// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SignTextHandle : RemoteTableHandle<EventContext, SignText>
        {
            protected override string RemoteTableName => "sign_text";

            public sealed class StructureIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(SignText row) => row.StructureId;

                public StructureIdUniqueIndex(SignTextHandle table) : base(table) { }
            }

            public readonly StructureIdUniqueIndex StructureId;

            internal SignTextHandle(DbConnection conn) : base(conn)
            {
                StructureId = new(this);
            }

            protected override object GetPrimaryKey(SignText row) => row.StructureId;
        }

        public readonly SignTextHandle SignText;
    }

    public sealed class SignTextCols
    {
        public global::SpacetimeDB.Col<SignText, ulong> StructureId { get; }
        public global::SpacetimeDB.Col<SignText, string> Text { get; }

        public SignTextCols(string tableName)
        {
            StructureId = new global::SpacetimeDB.Col<SignText, ulong>(tableName, "structure_id");
            Text = new global::SpacetimeDB.Col<SignText, string>(tableName, "text");
        }
    }

    public sealed class SignTextIxCols
    {
        public global::SpacetimeDB.IxCol<SignText, ulong> StructureId { get; }

        public SignTextIxCols(string tableName)
        {
            StructureId = new global::SpacetimeDB.IxCol<SignText, ulong>(tableName, "structure_id");
        }
    }
}
