// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TerrainConfigHandle : RemoteTableHandle<EventContext, TerrainConfig>
        {
            protected override string RemoteTableName => "terrain_config";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(TerrainConfig row) => row.Id;

                public IdUniqueIndex(TerrainConfigHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal TerrainConfigHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(TerrainConfig row) => row.Id;
        }

        public readonly TerrainConfigHandle TerrainConfig;
    }

    public sealed class TerrainConfigCols
    {
        public global::SpacetimeDB.Col<TerrainConfig, uint> Id { get; }
        public global::SpacetimeDB.Col<TerrainConfig, uint> Seed { get; }
        public global::SpacetimeDB.Col<TerrainConfig, float> WorldSize { get; }
        public global::SpacetimeDB.Col<TerrainConfig, float> NoiseScale { get; }
        public global::SpacetimeDB.Col<TerrainConfig, float> NoiseAmplitude { get; }

        public TerrainConfigCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<TerrainConfig, uint>(tableName, "id");
            Seed = new global::SpacetimeDB.Col<TerrainConfig, uint>(tableName, "seed");
            WorldSize = new global::SpacetimeDB.Col<TerrainConfig, float>(tableName, "world_size");
            NoiseScale = new global::SpacetimeDB.Col<TerrainConfig, float>(tableName, "noise_scale");
            NoiseAmplitude = new global::SpacetimeDB.Col<TerrainConfig, float>(tableName, "noise_amplitude");
        }
    }

    public sealed class TerrainConfigIxCols
    {
        public global::SpacetimeDB.IxCol<TerrainConfig, uint> Id { get; }

        public TerrainConfigIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<TerrainConfig, uint>(tableName, "id");
        }
    }
}
