// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WorldObjectHandle : RemoteTableHandle<EventContext, WorldObject>
        {
            protected override string RemoteTableName => "world_object";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(WorldObject row) => row.Id;

                public IdUniqueIndex(WorldObjectHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal WorldObjectHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(WorldObject row) => row.Id;
        }

        public readonly WorldObjectHandle WorldObject;
    }

    public sealed class WorldObjectCols
    {
        public global::SpacetimeDB.Col<WorldObject, ulong> Id { get; }
        public global::SpacetimeDB.Col<WorldObject, string> ObjectType { get; }
        public global::SpacetimeDB.Col<WorldObject, float> PosX { get; }
        public global::SpacetimeDB.Col<WorldObject, float> PosY { get; }
        public global::SpacetimeDB.Col<WorldObject, float> PosZ { get; }
        public global::SpacetimeDB.Col<WorldObject, float> RotY { get; }
        public global::SpacetimeDB.Col<WorldObject, uint> Health { get; }
        public global::SpacetimeDB.Col<WorldObject, uint> MaxHealth { get; }

        public WorldObjectCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<WorldObject, ulong>(tableName, "id");
            ObjectType = new global::SpacetimeDB.Col<WorldObject, string>(tableName, "object_type");
            PosX = new global::SpacetimeDB.Col<WorldObject, float>(tableName, "pos_x");
            PosY = new global::SpacetimeDB.Col<WorldObject, float>(tableName, "pos_y");
            PosZ = new global::SpacetimeDB.Col<WorldObject, float>(tableName, "pos_z");
            RotY = new global::SpacetimeDB.Col<WorldObject, float>(tableName, "rot_y");
            Health = new global::SpacetimeDB.Col<WorldObject, uint>(tableName, "health");
            MaxHealth = new global::SpacetimeDB.Col<WorldObject, uint>(tableName, "max_health");
        }
    }

    public sealed class WorldObjectIxCols
    {
        public global::SpacetimeDB.IxCol<WorldObject, ulong> Id { get; }

        public WorldObjectIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<WorldObject, ulong>(tableName, "id");
        }
    }
}
