// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ArcadeInputPatternHandler(ReducerEventContext ctx, ulong machineId, string playerSequence);
        public event ArcadeInputPatternHandler? OnArcadeInputPattern;

        public void ArcadeInputPattern(ulong machineId, string playerSequence)
        {
            conn.InternalCallReducer(new Reducer.ArcadeInputPattern(machineId, playerSequence));
        }

        public bool InvokeArcadeInputPattern(ReducerEventContext ctx, Reducer.ArcadeInputPattern args)
        {
            if (OnArcadeInputPattern == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnArcadeInputPattern(
                ctx,
                args.MachineId,
                args.PlayerSequence
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ArcadeInputPattern : Reducer, IReducerArgs
        {
            [DataMember(Name = "machine_id")]
            public ulong MachineId;
            [DataMember(Name = "player_sequence")]
            public string PlayerSequence;

            public ArcadeInputPattern(
                ulong MachineId,
                string PlayerSequence
            )
            {
                this.MachineId = MachineId;
                this.PlayerSequence = PlayerSequence;
            }

            public ArcadeInputPattern()
            {
                this.PlayerSequence = "";
            }

            string IReducerArgs.ReducerName => "arcade_input_pattern";
        }
    }
}
