// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ArcadeInputReactionHandler(ReducerEventContext ctx, ulong machineId);
        public event ArcadeInputReactionHandler? OnArcadeInputReaction;

        public void ArcadeInputReaction(ulong machineId)
        {
            conn.InternalCallReducer(new Reducer.ArcadeInputReaction(machineId));
        }

        public bool InvokeArcadeInputReaction(ReducerEventContext ctx, Reducer.ArcadeInputReaction args)
        {
            if (OnArcadeInputReaction == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnArcadeInputReaction(
                ctx,
                args.MachineId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ArcadeInputReaction : Reducer, IReducerArgs
        {
            [DataMember(Name = "machine_id")]
            public ulong MachineId;

            public ArcadeInputReaction(ulong MachineId)
            {
                this.MachineId = MachineId;
            }

            public ArcadeInputReaction()
            {
            }

            string IReducerArgs.ReducerName => "arcade_input_reaction";
        }
    }
}
