// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CleanupDamageEventsHandler(ReducerEventContext ctx);
        public event CleanupDamageEventsHandler? OnCleanupDamageEvents;

        public void CleanupDamageEvents()
        {
            conn.InternalCallReducer(new Reducer.CleanupDamageEvents());
        }

        public bool InvokeCleanupDamageEvents(ReducerEventContext ctx, Reducer.CleanupDamageEvents args)
        {
            if (OnCleanupDamageEvents == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCleanupDamageEvents(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CleanupDamageEvents : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "cleanup_damage_events";
        }
    }
}
