// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ContainerDepositHandler(ReducerEventContext ctx, ulong containerId, string containerTable, ulong inventoryItemId, int toSlot, uint quantity);
        public event ContainerDepositHandler? OnContainerDeposit;

        public void ContainerDeposit(ulong containerId, string containerTable, ulong inventoryItemId, int toSlot, uint quantity)
        {
            conn.InternalCallReducer(new Reducer.ContainerDeposit(containerId, containerTable, inventoryItemId, toSlot, quantity));
        }

        public bool InvokeContainerDeposit(ReducerEventContext ctx, Reducer.ContainerDeposit args)
        {
            if (OnContainerDeposit == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnContainerDeposit(
                ctx,
                args.ContainerId,
                args.ContainerTable,
                args.InventoryItemId,
                args.ToSlot,
                args.Quantity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ContainerDeposit : Reducer, IReducerArgs
        {
            [DataMember(Name = "container_id")]
            public ulong ContainerId;
            [DataMember(Name = "container_table")]
            public string ContainerTable;
            [DataMember(Name = "inventory_item_id")]
            public ulong InventoryItemId;
            [DataMember(Name = "to_slot")]
            public int ToSlot;
            [DataMember(Name = "quantity")]
            public uint Quantity;

            public ContainerDeposit(
                ulong ContainerId,
                string ContainerTable,
                ulong InventoryItemId,
                int ToSlot,
                uint Quantity
            )
            {
                this.ContainerId = ContainerId;
                this.ContainerTable = ContainerTable;
                this.InventoryItemId = InventoryItemId;
                this.ToSlot = ToSlot;
                this.Quantity = Quantity;
            }

            public ContainerDeposit()
            {
                this.ContainerTable = "";
            }

            string IReducerArgs.ReducerName => "container_deposit";
        }
    }
}
