// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ContainerWithdrawHandler(ReducerEventContext ctx, ulong containerId, string containerTable, int fromSlot, uint quantity);
        public event ContainerWithdrawHandler? OnContainerWithdraw;

        public void ContainerWithdraw(ulong containerId, string containerTable, int fromSlot, uint quantity)
        {
            conn.InternalCallReducer(new Reducer.ContainerWithdraw(containerId, containerTable, fromSlot, quantity));
        }

        public bool InvokeContainerWithdraw(ReducerEventContext ctx, Reducer.ContainerWithdraw args)
        {
            if (OnContainerWithdraw == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnContainerWithdraw(
                ctx,
                args.ContainerId,
                args.ContainerTable,
                args.FromSlot,
                args.Quantity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ContainerWithdraw : Reducer, IReducerArgs
        {
            [DataMember(Name = "container_id")]
            public ulong ContainerId;
            [DataMember(Name = "container_table")]
            public string ContainerTable;
            [DataMember(Name = "from_slot")]
            public int FromSlot;
            [DataMember(Name = "quantity")]
            public uint Quantity;

            public ContainerWithdraw(
                ulong ContainerId,
                string ContainerTable,
                int FromSlot,
                uint Quantity
            )
            {
                this.ContainerId = ContainerId;
                this.ContainerTable = ContainerTable;
                this.FromSlot = FromSlot;
                this.Quantity = Quantity;
            }

            public ContainerWithdraw()
            {
                this.ContainerTable = "";
            }

            string IReducerArgs.ReducerName => "container_withdraw";
        }
    }
}
