// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DamageWorldObjectHandler(ReducerEventContext ctx, ulong id, uint damage);
        public event DamageWorldObjectHandler? OnDamageWorldObject;

        public void DamageWorldObject(ulong id, uint damage)
        {
            conn.InternalCallReducer(new Reducer.DamageWorldObject(id, damage));
        }

        public bool InvokeDamageWorldObject(ReducerEventContext ctx, Reducer.DamageWorldObject args)
        {
            if (OnDamageWorldObject == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDamageWorldObject(
                ctx,
                args.Id,
                args.Damage
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DamageWorldObject : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public ulong Id;
            [DataMember(Name = "damage")]
            public uint Damage;

            public DamageWorldObject(
                ulong Id,
                uint Damage
            )
            {
                this.Id = Id;
                this.Damage = Damage;
            }

            public DamageWorldObject()
            {
            }

            string IReducerArgs.ReducerName => "damage_world_object";
        }
    }
}
