// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void FurnaceCollectHandler(ReducerEventContext ctx, ulong structureId);
        public event FurnaceCollectHandler? OnFurnaceCollect;

        public void FurnaceCollect(ulong structureId)
        {
            conn.InternalCallReducer(new Reducer.FurnaceCollect(structureId));
        }

        public bool InvokeFurnaceCollect(ReducerEventContext ctx, Reducer.FurnaceCollect args)
        {
            if (OnFurnaceCollect == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnFurnaceCollect(
                ctx,
                args.StructureId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class FurnaceCollect : Reducer, IReducerArgs
        {
            [DataMember(Name = "structure_id")]
            public ulong StructureId;

            public FurnaceCollect(ulong StructureId)
            {
                this.StructureId = StructureId;
            }

            public FurnaceCollect()
            {
            }

            string IReducerArgs.ReducerName => "furnace_collect";
        }
    }
}
