// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void GrantAdminHandler(ReducerEventContext ctx, SpacetimeDB.Identity target);
        public event GrantAdminHandler? OnGrantAdmin;

        public void GrantAdmin(SpacetimeDB.Identity target)
        {
            conn.InternalCallReducer(new Reducer.GrantAdmin(target));
        }

        public bool InvokeGrantAdmin(ReducerEventContext ctx, Reducer.GrantAdmin args)
        {
            if (OnGrantAdmin == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnGrantAdmin(
                ctx,
                args.Target
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class GrantAdmin : Reducer, IReducerArgs
        {
            [DataMember(Name = "target")]
            public SpacetimeDB.Identity Target;

            public GrantAdmin(SpacetimeDB.Identity Target)
            {
                this.Target = Target;
            }

            public GrantAdmin()
            {
            }

            string IReducerArgs.ReducerName => "grant_admin";
        }
    }
}
