// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void HarvestWorldObjectHandler(ReducerEventContext ctx, ulong id, string toolType);
        public event HarvestWorldObjectHandler? OnHarvestWorldObject;

        public void HarvestWorldObject(ulong id, string toolType)
        {
            conn.InternalCallReducer(new Reducer.HarvestWorldObject(id, toolType));
        }

        public bool InvokeHarvestWorldObject(ReducerEventContext ctx, Reducer.HarvestWorldObject args)
        {
            if (OnHarvestWorldObject == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnHarvestWorldObject(
                ctx,
                args.Id,
                args.ToolType
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class HarvestWorldObject : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public ulong Id;
            [DataMember(Name = "tool_type")]
            public string ToolType;

            public HarvestWorldObject(
                ulong Id,
                string ToolType
            )
            {
                this.Id = Id;
                this.ToolType = ToolType;
            }

            public HarvestWorldObject()
            {
                this.ToolType = "";
            }

            string IReducerArgs.ReducerName => "harvest_world_object";
        }
    }
}
