// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MoveItemToSlotHandler(ReducerEventContext ctx, ulong inventoryItemId, int slot);
        public event MoveItemToSlotHandler? OnMoveItemToSlot;

        public void MoveItemToSlot(ulong inventoryItemId, int slot)
        {
            conn.InternalCallReducer(new Reducer.MoveItemToSlot(inventoryItemId, slot));
        }

        public bool InvokeMoveItemToSlot(ReducerEventContext ctx, Reducer.MoveItemToSlot args)
        {
            if (OnMoveItemToSlot == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMoveItemToSlot(
                ctx,
                args.InventoryItemId,
                args.Slot
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MoveItemToSlot : Reducer, IReducerArgs
        {
            [DataMember(Name = "inventory_item_id")]
            public ulong InventoryItemId;
            [DataMember(Name = "slot")]
            public int Slot;

            public MoveItemToSlot(
                ulong InventoryItemId,
                int Slot
            )
            {
                this.InventoryItemId = InventoryItemId;
                this.Slot = Slot;
            }

            public MoveItemToSlot()
            {
            }

            string IReducerArgs.ReducerName => "move_item_to_slot";
        }
    }
}
