// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void NpcDealDamageHandler(ReducerEventContext ctx, ulong npcId, ulong targetId, string targetType, int amount, string damageType);
        public event NpcDealDamageHandler? OnNpcDealDamage;

        public void NpcDealDamage(ulong npcId, ulong targetId, string targetType, int amount, string damageType)
        {
            conn.InternalCallReducer(new Reducer.NpcDealDamage(npcId, targetId, targetType, amount, damageType));
        }

        public bool InvokeNpcDealDamage(ReducerEventContext ctx, Reducer.NpcDealDamage args)
        {
            if (OnNpcDealDamage == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnNpcDealDamage(
                ctx,
                args.NpcId,
                args.TargetId,
                args.TargetType,
                args.Amount,
                args.DamageType
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class NpcDealDamage : Reducer, IReducerArgs
        {
            [DataMember(Name = "npc_id")]
            public ulong NpcId;
            [DataMember(Name = "target_id")]
            public ulong TargetId;
            [DataMember(Name = "target_type")]
            public string TargetType;
            [DataMember(Name = "amount")]
            public int Amount;
            [DataMember(Name = "damage_type")]
            public string DamageType;

            public NpcDealDamage(
                ulong NpcId,
                ulong TargetId,
                string TargetType,
                int Amount,
                string DamageType
            )
            {
                this.NpcId = NpcId;
                this.TargetId = TargetId;
                this.TargetType = TargetType;
                this.Amount = Amount;
                this.DamageType = DamageType;
            }

            public NpcDealDamage()
            {
                this.TargetType = "";
                this.DamageType = "";
            }

            string IReducerArgs.ReducerName => "npc_deal_damage";
        }
    }
}
