// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void NpcSellItemHandler(ReducerEventContext ctx, ulong npcId, ulong inventoryItemId, uint quantity);
        public event NpcSellItemHandler? OnNpcSellItem;

        public void NpcSellItem(ulong npcId, ulong inventoryItemId, uint quantity)
        {
            conn.InternalCallReducer(new Reducer.NpcSellItem(npcId, inventoryItemId, quantity));
        }

        public bool InvokeNpcSellItem(ReducerEventContext ctx, Reducer.NpcSellItem args)
        {
            if (OnNpcSellItem == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnNpcSellItem(
                ctx,
                args.NpcId,
                args.InventoryItemId,
                args.Quantity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class NpcSellItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "npc_id")]
            public ulong NpcId;
            [DataMember(Name = "inventory_item_id")]
            public ulong InventoryItemId;
            [DataMember(Name = "quantity")]
            public uint Quantity;

            public NpcSellItem(
                ulong NpcId,
                ulong InventoryItemId,
                uint Quantity
            )
            {
                this.NpcId = NpcId;
                this.InventoryItemId = InventoryItemId;
                this.Quantity = Quantity;
            }

            public NpcSellItem()
            {
            }

            string IReducerArgs.ReducerName => "npc_sell_item";
        }
    }
}
