// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void NpcSetStateHandler(ReducerEventContext ctx, ulong npcId, string state, ulong targetEntityId, string targetEntityType);
        public event NpcSetStateHandler? OnNpcSetState;

        public void NpcSetState(ulong npcId, string state, ulong targetEntityId, string targetEntityType)
        {
            conn.InternalCallReducer(new Reducer.NpcSetState(npcId, state, targetEntityId, targetEntityType));
        }

        public bool InvokeNpcSetState(ReducerEventContext ctx, Reducer.NpcSetState args)
        {
            if (OnNpcSetState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnNpcSetState(
                ctx,
                args.NpcId,
                args.State,
                args.TargetEntityId,
                args.TargetEntityType
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class NpcSetState : Reducer, IReducerArgs
        {
            [DataMember(Name = "npc_id")]
            public ulong NpcId;
            [DataMember(Name = "state")]
            public string State;
            [DataMember(Name = "target_entity_id")]
            public ulong TargetEntityId;
            [DataMember(Name = "target_entity_type")]
            public string TargetEntityType;

            public NpcSetState(
                ulong NpcId,
                string State,
                ulong TargetEntityId,
                string TargetEntityType
            )
            {
                this.NpcId = NpcId;
                this.State = State;
                this.TargetEntityId = TargetEntityId;
                this.TargetEntityType = TargetEntityType;
            }

            public NpcSetState()
            {
                this.State = "";
                this.TargetEntityType = "";
            }

            string IReducerArgs.ReducerName => "npc_set_state";
        }
    }
}
