// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void NpcTradeHandler(ReducerEventContext ctx, ulong npcId, string buyItemType, uint quantity);
        public event NpcTradeHandler? OnNpcTrade;

        public void NpcTrade(ulong npcId, string buyItemType, uint quantity)
        {
            conn.InternalCallReducer(new Reducer.NpcTrade(npcId, buyItemType, quantity));
        }

        public bool InvokeNpcTrade(ReducerEventContext ctx, Reducer.NpcTrade args)
        {
            if (OnNpcTrade == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnNpcTrade(
                ctx,
                args.NpcId,
                args.BuyItemType,
                args.Quantity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class NpcTrade : Reducer, IReducerArgs
        {
            [DataMember(Name = "npc_id")]
            public ulong NpcId;
            [DataMember(Name = "buy_item_type")]
            public string BuyItemType;
            [DataMember(Name = "quantity")]
            public uint Quantity;

            public NpcTrade(
                ulong NpcId,
                string BuyItemType,
                uint Quantity
            )
            {
                this.NpcId = NpcId;
                this.BuyItemType = BuyItemType;
                this.Quantity = Quantity;
            }

            public NpcTrade()
            {
                this.BuyItemType = "";
            }

            string IReducerArgs.ReducerName => "npc_trade";
        }
    }
}
