// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlaceBetHandler(ReducerEventContext ctx, ulong machineId, ulong amount);
        public event PlaceBetHandler? OnPlaceBet;

        public void PlaceBet(ulong machineId, ulong amount)
        {
            conn.InternalCallReducer(new Reducer.PlaceBet(machineId, amount));
        }

        public bool InvokePlaceBet(ReducerEventContext ctx, Reducer.PlaceBet args)
        {
            if (OnPlaceBet == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlaceBet(
                ctx,
                args.MachineId,
                args.Amount
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlaceBet : Reducer, IReducerArgs
        {
            [DataMember(Name = "machine_id")]
            public ulong MachineId;
            [DataMember(Name = "amount")]
            public ulong Amount;

            public PlaceBet(
                ulong MachineId,
                ulong Amount
            )
            {
                this.MachineId = MachineId;
                this.Amount = Amount;
            }

            public PlaceBet()
            {
            }

            string IReducerArgs.ReducerName => "place_bet";
        }
    }
}
