// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PushCoinHandler(ReducerEventContext ctx, ulong machineId, ulong copperAmount);
        public event PushCoinHandler? OnPushCoin;

        public void PushCoin(ulong machineId, ulong copperAmount)
        {
            conn.InternalCallReducer(new Reducer.PushCoin(machineId, copperAmount));
        }

        public bool InvokePushCoin(ReducerEventContext ctx, Reducer.PushCoin args)
        {
            if (OnPushCoin == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPushCoin(
                ctx,
                args.MachineId,
                args.CopperAmount
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PushCoin : Reducer, IReducerArgs
        {
            [DataMember(Name = "machine_id")]
            public ulong MachineId;
            [DataMember(Name = "copper_amount")]
            public ulong CopperAmount;

            public PushCoin(
                ulong MachineId,
                ulong CopperAmount
            )
            {
                this.MachineId = MachineId;
                this.CopperAmount = CopperAmount;
            }

            public PushCoin()
            {
            }

            string IReducerArgs.ReducerName => "push_coin";
        }
    }
}
