// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RegisterServiceIdentityHandler(ReducerEventContext ctx);
        public event RegisterServiceIdentityHandler? OnRegisterServiceIdentity;

        public void RegisterServiceIdentity()
        {
            conn.InternalCallReducer(new Reducer.RegisterServiceIdentity());
        }

        public bool InvokeRegisterServiceIdentity(ReducerEventContext ctx, Reducer.RegisterServiceIdentity args)
        {
            if (OnRegisterServiceIdentity == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRegisterServiceIdentity(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RegisterServiceIdentity : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "register_service_identity";
        }
    }
}
