// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ReleaseSlotHandler(ReducerEventContext ctx, ulong machineId);
        public event ReleaseSlotHandler? OnReleaseSlot;

        public void ReleaseSlot(ulong machineId)
        {
            conn.InternalCallReducer(new Reducer.ReleaseSlot(machineId));
        }

        public bool InvokeReleaseSlot(ReducerEventContext ctx, Reducer.ReleaseSlot args)
        {
            if (OnReleaseSlot == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnReleaseSlot(
                ctx,
                args.MachineId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ReleaseSlot : Reducer, IReducerArgs
        {
            [DataMember(Name = "machine_id")]
            public ulong MachineId;

            public ReleaseSlot(ulong MachineId)
            {
                this.MachineId = MachineId;
            }

            public ReleaseSlot()
            {
            }

            string IReducerArgs.ReducerName => "release_slot";
        }
    }
}
