// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetModEnabledHandler(ReducerEventContext ctx, string modId, bool enabled);
        public event SetModEnabledHandler? OnSetModEnabled;

        public void SetModEnabled(string modId, bool enabled)
        {
            conn.InternalCallReducer(new Reducer.SetModEnabled(modId, enabled));
        }

        public bool InvokeSetModEnabled(ReducerEventContext ctx, Reducer.SetModEnabled args)
        {
            if (OnSetModEnabled == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetModEnabled(
                ctx,
                args.ModId,
                args.Enabled
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetModEnabled : Reducer, IReducerArgs
        {
            [DataMember(Name = "mod_id")]
            public string ModId;
            [DataMember(Name = "enabled")]
            public bool Enabled;

            public SetModEnabled(
                string ModId,
                bool Enabled
            )
            {
                this.ModId = ModId;
                this.Enabled = Enabled;
            }

            public SetModEnabled()
            {
                this.ModId = "";
            }

            string IReducerArgs.ReducerName => "set_mod_enabled";
        }
    }
}
