// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SkipSeatHandler(ReducerEventContext ctx, ulong machineId, byte seatIndex);
        public event SkipSeatHandler? OnSkipSeat;

        public void SkipSeat(ulong machineId, byte seatIndex)
        {
            conn.InternalCallReducer(new Reducer.SkipSeat(machineId, seatIndex));
        }

        public bool InvokeSkipSeat(ReducerEventContext ctx, Reducer.SkipSeat args)
        {
            if (OnSkipSeat == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSkipSeat(
                ctx,
                args.MachineId,
                args.SeatIndex
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SkipSeat : Reducer, IReducerArgs
        {
            [DataMember(Name = "machine_id")]
            public ulong MachineId;
            [DataMember(Name = "seat_index")]
            public byte SeatIndex;

            public SkipSeat(
                ulong MachineId,
                byte SeatIndex
            )
            {
                this.MachineId = MachineId;
                this.SeatIndex = SeatIndex;
            }

            public SkipSeat()
            {
            }

            string IReducerArgs.ReducerName => "skip_seat";
        }
    }
}
