// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SpawnNpcHandler(ReducerEventContext ctx, string npcType, float x, float y, float z, float rotY);
        public event SpawnNpcHandler? OnSpawnNpc;

        public void SpawnNpc(string npcType, float x, float y, float z, float rotY)
        {
            conn.InternalCallReducer(new Reducer.SpawnNpc(npcType, x, y, z, rotY));
        }

        public bool InvokeSpawnNpc(ReducerEventContext ctx, Reducer.SpawnNpc args)
        {
            if (OnSpawnNpc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSpawnNpc(
                ctx,
                args.NpcType,
                args.X,
                args.Y,
                args.Z,
                args.RotY
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SpawnNpc : Reducer, IReducerArgs
        {
            [DataMember(Name = "npc_type")]
            public string NpcType;
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "z")]
            public float Z;
            [DataMember(Name = "rot_y")]
            public float RotY;

            public SpawnNpc(
                string NpcType,
                float X,
                float Y,
                float Z,
                float RotY
            )
            {
                this.NpcType = NpcType;
                this.X = X;
                this.Y = Y;
                this.Z = Z;
                this.RotY = RotY;
            }

            public SpawnNpc()
            {
                this.NpcType = "";
            }

            string IReducerArgs.ReducerName => "spawn_npc";
        }
    }
}
