// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SpinSlotHandler(ReducerEventContext ctx, ulong machineId, ulong betAmount);
        public event SpinSlotHandler? OnSpinSlot;

        public void SpinSlot(ulong machineId, ulong betAmount)
        {
            conn.InternalCallReducer(new Reducer.SpinSlot(machineId, betAmount));
        }

        public bool InvokeSpinSlot(ReducerEventContext ctx, Reducer.SpinSlot args)
        {
            if (OnSpinSlot == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSpinSlot(
                ctx,
                args.MachineId,
                args.BetAmount
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SpinSlot : Reducer, IReducerArgs
        {
            [DataMember(Name = "machine_id")]
            public ulong MachineId;
            [DataMember(Name = "bet_amount")]
            public ulong BetAmount;

            public SpinSlot(
                ulong MachineId,
                ulong BetAmount
            )
            {
                this.MachineId = MachineId;
                this.BetAmount = BetAmount;
            }

            public SpinSlot()
            {
            }

            string IReducerArgs.ReducerName => "spin_slot";
        }
    }
}
