// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StandBlackjackHandler(ReducerEventContext ctx, ulong machineId);
        public event StandBlackjackHandler? OnStandBlackjack;

        public void StandBlackjack(ulong machineId)
        {
            conn.InternalCallReducer(new Reducer.StandBlackjack(machineId));
        }

        public bool InvokeStandBlackjack(ReducerEventContext ctx, Reducer.StandBlackjack args)
        {
            if (OnStandBlackjack == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStandBlackjack(
                ctx,
                args.MachineId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StandBlackjack : Reducer, IReducerArgs
        {
            [DataMember(Name = "machine_id")]
            public ulong MachineId;

            public StandBlackjack(ulong MachineId)
            {
                this.MachineId = MachineId;
            }

            public StandBlackjack()
            {
            }

            string IReducerArgs.ReducerName => "stand_blackjack";
        }
    }
}
