// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StartArcadeHandler(ReducerEventContext ctx, ulong machineId, ulong bet);
        public event StartArcadeHandler? OnStartArcade;

        public void StartArcade(ulong machineId, ulong bet)
        {
            conn.InternalCallReducer(new Reducer.StartArcade(machineId, bet));
        }

        public bool InvokeStartArcade(ReducerEventContext ctx, Reducer.StartArcade args)
        {
            if (OnStartArcade == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStartArcade(
                ctx,
                args.MachineId,
                args.Bet
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StartArcade : Reducer, IReducerArgs
        {
            [DataMember(Name = "machine_id")]
            public ulong MachineId;
            [DataMember(Name = "bet")]
            public ulong Bet;

            public StartArcade(
                ulong MachineId,
                ulong Bet
            )
            {
                this.MachineId = MachineId;
                this.Bet = Bet;
            }

            public StartArcade()
            {
            }

            string IReducerArgs.ReducerName => "start_arcade";
        }
    }
}
