// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StartBlackjackRoundHandler(ReducerEventContext ctx, ulong machineId);
        public event StartBlackjackRoundHandler? OnStartBlackjackRound;

        public void StartBlackjackRound(ulong machineId)
        {
            conn.InternalCallReducer(new Reducer.StartBlackjackRound(machineId));
        }

        public bool InvokeStartBlackjackRound(ReducerEventContext ctx, Reducer.StartBlackjackRound args)
        {
            if (OnStartBlackjackRound == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStartBlackjackRound(
                ctx,
                args.MachineId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StartBlackjackRound : Reducer, IReducerArgs
        {
            [DataMember(Name = "machine_id")]
            public ulong MachineId;

            public StartBlackjackRound(ulong MachineId)
            {
                this.MachineId = MachineId;
            }

            public StartBlackjackRound()
            {
            }

            string IReducerArgs.ReducerName => "start_blackjack_round";
        }
    }
}
