// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateSignTextHandler(ReducerEventContext ctx, ulong structureId, string text);
        public event UpdateSignTextHandler? OnUpdateSignText;

        public void UpdateSignText(ulong structureId, string text)
        {
            conn.InternalCallReducer(new Reducer.UpdateSignText(structureId, text));
        }

        public bool InvokeUpdateSignText(ReducerEventContext ctx, Reducer.UpdateSignText args)
        {
            if (OnUpdateSignText == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateSignText(
                ctx,
                args.StructureId,
                args.Text
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateSignText : Reducer, IReducerArgs
        {
            [DataMember(Name = "structure_id")]
            public ulong StructureId;
            [DataMember(Name = "text")]
            public string Text;

            public UpdateSignText(
                ulong StructureId,
                string Text
            )
            {
                this.StructureId = StructureId;
                this.Text = Text;
            }

            public UpdateSignText()
            {
                this.Text = "";
            }

            string IReducerArgs.ReducerName => "update_sign_text";
        }
    }
}
