// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void WithdrawCoinsHandler(ReducerEventContext ctx, string denomination, uint amount);
        public event WithdrawCoinsHandler? OnWithdrawCoins;

        public void WithdrawCoins(string denomination, uint amount)
        {
            conn.InternalCallReducer(new Reducer.WithdrawCoins(denomination, amount));
        }

        public bool InvokeWithdrawCoins(ReducerEventContext ctx, Reducer.WithdrawCoins args)
        {
            if (OnWithdrawCoins == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnWithdrawCoins(
                ctx,
                args.Denomination,
                args.Amount
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class WithdrawCoins : Reducer, IReducerArgs
        {
            [DataMember(Name = "denomination")]
            public string Denomination;
            [DataMember(Name = "amount")]
            public uint Amount;

            public WithdrawCoins(
                string Denomination,
                uint Amount
            )
            {
                this.Denomination = Denomination;
                this.Amount = Amount;
            }

            public WithdrawCoins()
            {
                this.Denomination = "";
            }

            string IReducerArgs.ReducerName => "withdraw_coins";
        }
    }
}
