// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ContainerTransferHandler(ReducerEventContext ctx, ulong containerId, string containerTable, int fromSlot, int toSlot);
        public event ContainerTransferHandler? OnContainerTransfer;

        public void ContainerTransfer(ulong containerId, string containerTable, int fromSlot, int toSlot)
        {
            conn.InternalCallReducer(new Reducer.ContainerTransfer(containerId, containerTable, fromSlot, toSlot));
        }

        public bool InvokeContainerTransfer(ReducerEventContext ctx, Reducer.ContainerTransfer args)
        {
            if (OnContainerTransfer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnContainerTransfer(
                ctx,
                args.ContainerId,
                args.ContainerTable,
                args.FromSlot,
                args.ToSlot
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ContainerTransfer : Reducer, IReducerArgs
        {
            [DataMember(Name = "container_id")]
            public ulong ContainerId;
            [DataMember(Name = "container_table")]
            public string ContainerTable;
            [DataMember(Name = "from_slot")]
            public int FromSlot;
            [DataMember(Name = "to_slot")]
            public int ToSlot;

            public ContainerTransfer(
                ulong ContainerId,
                string ContainerTable,
                int FromSlot,
                int ToSlot
            )
            {
                this.ContainerId = ContainerId;
                this.ContainerTable = ContainerTable;
                this.FromSlot = FromSlot;
                this.ToSlot = ToSlot;
            }

            public ContainerTransfer()
            {
                this.ContainerTable = "";
            }

            string IReducerArgs.ReducerName => "container_transfer";
        }
    }
}
