// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CraftItemHandler(ReducerEventContext ctx, ulong recipeId, string station);
        public event CraftItemHandler? OnCraftItem;

        public void CraftItem(ulong recipeId, string station)
        {
            conn.InternalCallReducer(new Reducer.CraftItem(recipeId, station));
        }

        public bool InvokeCraftItem(ReducerEventContext ctx, Reducer.CraftItem args)
        {
            if (OnCraftItem == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCraftItem(
                ctx,
                args.RecipeId,
                args.Station
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CraftItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "recipe_id")]
            public ulong RecipeId;
            [DataMember(Name = "station")]
            public string Station;

            public CraftItem(
                ulong RecipeId,
                string Station
            )
            {
                this.RecipeId = RecipeId;
                this.Station = Station;
            }

            public CraftItem()
            {
                this.Station = "";
            }

            string IReducerArgs.ReducerName => "craft_item";
        }
    }
}
