// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void FurnaceStartSmeltHandler(ReducerEventContext ctx, ulong structureId);
        public event FurnaceStartSmeltHandler? OnFurnaceStartSmelt;

        public void FurnaceStartSmelt(ulong structureId)
        {
            conn.InternalCallReducer(new Reducer.FurnaceStartSmelt(structureId));
        }

        public bool InvokeFurnaceStartSmelt(ReducerEventContext ctx, Reducer.FurnaceStartSmelt args)
        {
            if (OnFurnaceStartSmelt == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnFurnaceStartSmelt(
                ctx,
                args.StructureId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class FurnaceStartSmelt : Reducer, IReducerArgs
        {
            [DataMember(Name = "structure_id")]
            public ulong StructureId;

            public FurnaceStartSmelt(ulong StructureId)
            {
                this.StructureId = StructureId;
            }

            public FurnaceStartSmelt()
            {
            }

            string IReducerArgs.ReducerName => "furnace_start_smelt";
        }
    }
}
