// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MovePlayerHandler(ReducerEventContext ctx, float posX, float posY, float posZ, float rotY);
        public event MovePlayerHandler? OnMovePlayer;

        public void MovePlayer(float posX, float posY, float posZ, float rotY)
        {
            conn.InternalCallReducer(new Reducer.MovePlayer(posX, posY, posZ, rotY));
        }

        public bool InvokeMovePlayer(ReducerEventContext ctx, Reducer.MovePlayer args)
        {
            if (OnMovePlayer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMovePlayer(
                ctx,
                args.PosX,
                args.PosY,
                args.PosZ,
                args.RotY
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MovePlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "pos_x")]
            public float PosX;
            [DataMember(Name = "pos_y")]
            public float PosY;
            [DataMember(Name = "pos_z")]
            public float PosZ;
            [DataMember(Name = "rot_y")]
            public float RotY;

            public MovePlayer(
                float PosX,
                float PosY,
                float PosZ,
                float RotY
            )
            {
                this.PosX = PosX;
                this.PosY = PosY;
                this.PosZ = PosZ;
                this.RotY = RotY;
            }

            public MovePlayer()
            {
            }

            string IReducerArgs.ReducerName => "move_player";
        }
    }
}
