// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void NpcDealDamageToPlayerHandler(ReducerEventContext ctx, ulong npcId, string targetIdentityHex, int amount, string damageType);
        public event NpcDealDamageToPlayerHandler? OnNpcDealDamageToPlayer;

        public void NpcDealDamageToPlayer(ulong npcId, string targetIdentityHex, int amount, string damageType)
        {
            conn.InternalCallReducer(new Reducer.NpcDealDamageToPlayer(npcId, targetIdentityHex, amount, damageType));
        }

        public bool InvokeNpcDealDamageToPlayer(ReducerEventContext ctx, Reducer.NpcDealDamageToPlayer args)
        {
            if (OnNpcDealDamageToPlayer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnNpcDealDamageToPlayer(
                ctx,
                args.NpcId,
                args.TargetIdentityHex,
                args.Amount,
                args.DamageType
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class NpcDealDamageToPlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "npc_id")]
            public ulong NpcId;
            [DataMember(Name = "target_identity_hex")]
            public string TargetIdentityHex;
            [DataMember(Name = "amount")]
            public int Amount;
            [DataMember(Name = "damage_type")]
            public string DamageType;

            public NpcDealDamageToPlayer(
                ulong NpcId,
                string TargetIdentityHex,
                int Amount,
                string DamageType
            )
            {
                this.NpcId = NpcId;
                this.TargetIdentityHex = TargetIdentityHex;
                this.Amount = Amount;
                this.DamageType = DamageType;
            }

            public NpcDealDamageToPlayer()
            {
                this.TargetIdentityHex = "";
                this.DamageType = "";
            }

            string IReducerArgs.ReducerName => "npc_deal_damage_to_player";
        }
    }
}
