// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void NpcMoveHandler(ReducerEventContext ctx, ulong npcId, float x, float y, float z, float rotY);
        public event NpcMoveHandler? OnNpcMove;

        public void NpcMove(ulong npcId, float x, float y, float z, float rotY)
        {
            conn.InternalCallReducer(new Reducer.NpcMove(npcId, x, y, z, rotY));
        }

        public bool InvokeNpcMove(ReducerEventContext ctx, Reducer.NpcMove args)
        {
            if (OnNpcMove == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnNpcMove(
                ctx,
                args.NpcId,
                args.X,
                args.Y,
                args.Z,
                args.RotY
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class NpcMove : Reducer, IReducerArgs
        {
            [DataMember(Name = "npc_id")]
            public ulong NpcId;
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "z")]
            public float Z;
            [DataMember(Name = "rot_y")]
            public float RotY;

            public NpcMove(
                ulong NpcId,
                float X,
                float Y,
                float Z,
                float RotY
            )
            {
                this.NpcId = NpcId;
                this.X = X;
                this.Y = Y;
                this.Z = Z;
                this.RotY = RotY;
            }

            public NpcMove()
            {
            }

            string IReducerArgs.ReducerName => "npc_move";
        }
    }
}
