// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlaceStructureHandler(ReducerEventContext ctx, string structureType, float posX, float posY, float posZ, float rotY);
        public event PlaceStructureHandler? OnPlaceStructure;

        public void PlaceStructure(string structureType, float posX, float posY, float posZ, float rotY)
        {
            conn.InternalCallReducer(new Reducer.PlaceStructure(structureType, posX, posY, posZ, rotY));
        }

        public bool InvokePlaceStructure(ReducerEventContext ctx, Reducer.PlaceStructure args)
        {
            if (OnPlaceStructure == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlaceStructure(
                ctx,
                args.StructureType,
                args.PosX,
                args.PosY,
                args.PosZ,
                args.RotY
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlaceStructure : Reducer, IReducerArgs
        {
            [DataMember(Name = "structure_type")]
            public string StructureType;
            [DataMember(Name = "pos_x")]
            public float PosX;
            [DataMember(Name = "pos_y")]
            public float PosY;
            [DataMember(Name = "pos_z")]
            public float PosZ;
            [DataMember(Name = "rot_y")]
            public float RotY;

            public PlaceStructure(
                string StructureType,
                float PosX,
                float PosY,
                float PosZ,
                float RotY
            )
            {
                this.StructureType = StructureType;
                this.PosX = PosX;
                this.PosY = PosY;
                this.PosZ = PosZ;
                this.RotY = RotY;
            }

            public PlaceStructure()
            {
                this.StructureType = "";
            }

            string IReducerArgs.ReducerName => "place_structure";
        }
    }
}
