// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerAttackPlayerHandler(ReducerEventContext ctx, string targetIdentityHex);
        public event PlayerAttackPlayerHandler? OnPlayerAttackPlayer;

        public void PlayerAttackPlayer(string targetIdentityHex)
        {
            conn.InternalCallReducer(new Reducer.PlayerAttackPlayer(targetIdentityHex));
        }

        public bool InvokePlayerAttackPlayer(ReducerEventContext ctx, Reducer.PlayerAttackPlayer args)
        {
            if (OnPlayerAttackPlayer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerAttackPlayer(
                ctx,
                args.TargetIdentityHex
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerAttackPlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "target_identity_hex")]
            public string TargetIdentityHex;

            public PlayerAttackPlayer(string TargetIdentityHex)
            {
                this.TargetIdentityHex = TargetIdentityHex;
            }

            public PlayerAttackPlayer()
            {
                this.TargetIdentityHex = "";
            }

            string IReducerArgs.ReducerName => "player_attack_player";
        }
    }
}
