// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerAttackNpcHandler(ReducerEventContext ctx, ulong npcId);
        public event PlayerAttackNpcHandler? OnPlayerAttackNpc;

        public void PlayerAttackNpc(ulong npcId)
        {
            conn.InternalCallReducer(new Reducer.PlayerAttackNpc(npcId));
        }

        public bool InvokePlayerAttackNpc(ReducerEventContext ctx, Reducer.PlayerAttackNpc args)
        {
            if (OnPlayerAttackNpc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerAttackNpc(
                ctx,
                args.NpcId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerAttackNpc : Reducer, IReducerArgs
        {
            [DataMember(Name = "npc_id")]
            public ulong NpcId;

            public PlayerAttackNpc(ulong NpcId)
            {
                this.NpcId = NpcId;
            }

            public PlayerAttackNpc()
            {
            }

            string IReducerArgs.ReducerName => "player_attack_npc";
        }
    }
}
