// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RemoveStructureHandler(ReducerEventContext ctx, ulong structureId);
        public event RemoveStructureHandler? OnRemoveStructure;

        public void RemoveStructure(ulong structureId)
        {
            conn.InternalCallReducer(new Reducer.RemoveStructure(structureId));
        }

        public bool InvokeRemoveStructure(ReducerEventContext ctx, Reducer.RemoveStructure args)
        {
            if (OnRemoveStructure == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRemoveStructure(
                ctx,
                args.StructureId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RemoveStructure : Reducer, IReducerArgs
        {
            [DataMember(Name = "structure_id")]
            public ulong StructureId;

            public RemoveStructure(ulong StructureId)
            {
                this.StructureId = StructureId;
            }

            public RemoveStructure()
            {
            }

            string IReducerArgs.ReducerName => "remove_structure";
        }
    }
}
