// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ToggleAccessControlHandler(ReducerEventContext ctx, ulong entityId, string entityTable);
        public event ToggleAccessControlHandler? OnToggleAccessControl;

        public void ToggleAccessControl(ulong entityId, string entityTable)
        {
            conn.InternalCallReducer(new Reducer.ToggleAccessControl(entityId, entityTable));
        }

        public bool InvokeToggleAccessControl(ReducerEventContext ctx, Reducer.ToggleAccessControl args)
        {
            if (OnToggleAccessControl == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnToggleAccessControl(
                ctx,
                args.EntityId,
                args.EntityTable
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ToggleAccessControl : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity_id")]
            public ulong EntityId;
            [DataMember(Name = "entity_table")]
            public string EntityTable;

            public ToggleAccessControl(
                ulong EntityId,
                string EntityTable
            )
            {
                this.EntityId = EntityId;
                this.EntityTable = EntityTable;
            }

            public ToggleAccessControl()
            {
                this.EntityTable = "";
            }

            string IReducerArgs.ReducerName => "toggle_access_control";
        }
    }
}
