// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ChatMessage
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "sender_id")]
        public SpacetimeDB.Identity SenderId;
        [DataMember(Name = "sender_name")]
        public string SenderName;
        [DataMember(Name = "text")]
        public string Text;
        [DataMember(Name = "timestamp")]
        public ulong Timestamp;

        public ChatMessage(
            ulong Id,
            SpacetimeDB.Identity SenderId,
            string SenderName,
            string Text,
            ulong Timestamp
        )
        {
            this.Id = Id;
            this.SenderId = SenderId;
            this.SenderName = SenderName;
            this.Text = Text;
            this.Timestamp = Timestamp;
        }

        public ChatMessage()
        {
            this.SenderName = "";
            this.Text = "";
        }
    }
}
