// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class HelloWorldMessage
    {
        [DataMember(Name = "player_id")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "message")]
        public string Message;

        public HelloWorldMessage(
            SpacetimeDB.Identity PlayerId,
            string Message
        )
        {
            this.PlayerId = PlayerId;
            this.Message = Message;
        }

        public HelloWorldMessage()
        {
            this.Message = "";
        }
    }
}
