// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NpcConfig
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "npc_type")]
        public string NpcType;
        [DataMember(Name = "max_health")]
        public int MaxHealth;
        [DataMember(Name = "attack_damage")]
        public int AttackDamage;
        [DataMember(Name = "attack_range")]
        public float AttackRange;
        [DataMember(Name = "attack_cooldown_ms")]
        public ulong AttackCooldownMs;
        [DataMember(Name = "is_attackable")]
        public bool IsAttackable;
        [DataMember(Name = "is_trader")]
        public bool IsTrader;
        [DataMember(Name = "has_dialogue")]
        public bool HasDialogue;

        public NpcConfig(
            ulong Id,
            string NpcType,
            int MaxHealth,
            int AttackDamage,
            float AttackRange,
            ulong AttackCooldownMs,
            bool IsAttackable,
            bool IsTrader,
            bool HasDialogue
        )
        {
            this.Id = Id;
            this.NpcType = NpcType;
            this.MaxHealth = MaxHealth;
            this.AttackDamage = AttackDamage;
            this.AttackRange = AttackRange;
            this.AttackCooldownMs = AttackCooldownMs;
            this.IsAttackable = IsAttackable;
            this.IsTrader = IsTrader;
            this.HasDialogue = HasDialogue;
        }

        public NpcConfig()
        {
            this.NpcType = "";
        }
    }
}
