// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlacedStructure
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "owner_id")]
        public SpacetimeDB.Identity OwnerId;
        [DataMember(Name = "structure_type")]
        public string StructureType;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_y")]
        public float PosY;
        [DataMember(Name = "pos_z")]
        public float PosZ;
        [DataMember(Name = "rot_y")]
        public float RotY;
        [DataMember(Name = "health")]
        public float Health;
        [DataMember(Name = "max_health")]
        public float MaxHealth;

        public PlacedStructure(
            ulong Id,
            SpacetimeDB.Identity OwnerId,
            string StructureType,
            float PosX,
            float PosY,
            float PosZ,
            float RotY,
            float Health,
            float MaxHealth
        )
        {
            this.Id = Id;
            this.OwnerId = OwnerId;
            this.StructureType = StructureType;
            this.PosX = PosX;
            this.PosY = PosY;
            this.PosZ = PosZ;
            this.RotY = RotY;
            this.Health = Health;
            this.MaxHealth = MaxHealth;
        }

        public PlacedStructure()
        {
            this.StructureType = "";
        }
    }
}
