// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ServiceIdentity
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "service_id")]
        public SpacetimeDB.Identity ServiceId;

        public ServiceIdentity(
            ulong Id,
            SpacetimeDB.Identity ServiceId
        )
        {
            this.Id = Id;
            this.ServiceId = ServiceId;
        }

        public ServiceIdentity()
        {
        }
    }
}
