// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TerrainConfig
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "seed")]
        public uint Seed;
        [DataMember(Name = "world_size")]
        public float WorldSize;
        [DataMember(Name = "noise_scale")]
        public float NoiseScale;
        [DataMember(Name = "noise_amplitude")]
        public float NoiseAmplitude;

        public TerrainConfig(
            uint Id,
            uint Seed,
            float WorldSize,
            float NoiseScale,
            float NoiseAmplitude
        )
        {
            this.Id = Id;
            this.Seed = Seed;
            this.WorldSize = WorldSize;
            this.NoiseScale = NoiseScale;
            this.NoiseAmplitude = NoiseAmplitude;
        }

        public TerrainConfig()
        {
        }
    }
}
